@host = http://localhost:5000

###Create Like
POST {{host}}/v1/api/likes HTTP/1.1
content-type: application/json

{
  "like": 
    {
    "emoji" : "hehe",
    "likeable_type" :"Like/Comment",
    "likeable_id" : "174be2cd-ed9a-4534-89f5-a982944aac84",
    "user_id" :"526c0b00-677d-11ee-8390-0242ac150004"
    }
}

###Update Like
PUT {{host}}/v1/api/likes/07e314e7-bee1-411f-bb94-820c74f124b2 HTTP/1.1
content-type: application/json

{
  "like": 
    {
    "id":"733e10b3-25a6-4bf1-b276-8724d913700c",
    "name" : "TEAM DEV 3",
    "description" :"who is that",
    "status" : 1,
    "user_id" :"526c0b00-677d-11ee-8390-0242ac150004"
    }
  
}

###Get Like
GET {{host}}/v1/api/likes/07e314e7-bee1-411f-bb94-820c74f124b2 HTTP/1.1
content-type: application/json

{}

###Delete Like
DELETE  {{host}}/v1/api/likes/a5ffee90-879b-4b30-b9b8-d732605a658b HTTP/1.1
content-type: application/json

{}