@host = http://localhost:5000

###Create Comment
POST {{host}}/v1/api/comments HTTP/1.1
content-type: application/json

{
  "comment": 
    {
    "post_id" : "120d1c98-4cb9-499d-9ddd-01351ddb3781",
    "user_id" :"526c0b00-677d-11ee-8390-0242ac150004",
    //"reply_to_id" : 1,
    "content" :"Hello my friend"
    }
}

###Create Comment Has Parent
POST {{host}}/v1/api/comments HTTP/1.1
content-type: application/json

{
  "comment": 
    {
    "post_id" : "3b68c889-c24c-4e53-90e4-807fcdb1a6b1",
    "user_id" :"526c0b00-677d-11ee-8390-0242ac150004",
    //"reply_to_id" : 1,
    "content" :"Hello 3",
    "parent_comment_id" : "2d21ca29-a9c9-4da3-8807-f50c364a0eb6"
    }
}

###Update Comment
PUT {{host}}/v1/api/comments/3de6407d-d10b-4cf7-a4ae-267253a47335 HTTP/1.1
content-type: application/json

{
  "comment": 
    {
      "content" :"Reply comment"
    }
  
}

###Get Comment By PostID
GET {{host}}/v1/api/posts/3b68c889-c24c-4e53-90e4-807fcdb1a6b1/comments HTTP/1.1
content-type: application/json

{}

###Get Comment
GET {{host}}/v1/api/comments/852daf12-7676-46aa-aa14-053dc9ee84aa HTTP/1.1
content-type: application/json

{}

###Delete Comment
DELETE  {{host}}/v1/api/comments/852daf12-7676-46aa-aa14-053dc9ee84aa HTTP/1.1
content-type: application/json

{}