@host = http://localhost:5000

###Create Post
POST {{host}}/v1/api/posts HTTP/1.1
content-type: application/json

{
  "post": 
    {
    "title" : "Hom nay la ngay 16/10/2023",
    "content" :"who is that who is that",
    "status" : 1,
    "user_id" :"526c0b00-677d-11ee-8390-0242ac150004"
    }
  
}

###Create Post Group
POST {{host}}/v1/api/posts HTTP/1.1
content-type: application/json

{
  "post": 
    {
    "title" : "Hom nay la ngay 16/10/2023",
    "content" :"who is that who is that",
    "status" : 1,
    "user_id" :"526c0b00-677d-11ee-8390-0242ac150004",
    "group_id": "8d694e9c-1a35-4c98-97d6-14838c0de767"
    }
  
}

###Update Post
PUT {{host}}/v1/api/posts/51bd5a4f-c1b2-4163-bb90-d80b9d24a369 HTTP/1.1
content-type: application/json

{
  "post": 
    {
    //"title" : "Hom nay la ngay 20/10/2023"
    "content" :"who is that"
    //"status" : 1
    }
}

###Get Post
GET {{host}}/v1/api/posts/51bd5a4f-c1b2-4163-bb90-d80b9d24a369 HTTP/1.1
content-type: application/json

{}

###Delete Post
DELETE  {{host}}/v1/api/posts/51bd5a4f-c1b2-4163-bb90-d80b9d24a369 HTTP/1.1
content-type: application/json

{}