@host = http://localhost:5000

###
POST {{host}}/v1/api/groups HTTP/1.1
content-type: application/json

{
  "group": 
    {
    "name" : "TEAM DEV",
    "description" :"who",
    "status" : 1,
    "user_id" :"abc0"
    }
  
}

###
GET {{host}}/v1/api/groups/abc HTTP/1.1
content-type: application/json

{}