@host = http://localhost:5000

###Create Comment
POST {{host}}/v1/api/comments HTTP/1.1
content-type: application/json

{
  "comment": 
    {
    "post_id" : "e4a448b6-278b-4a41-a936-9e2003fcee71",
    "user_id" :"526c0b00-677d-11ee-8390-0242ac150004",
    //"reply_to_id" : 1,
    "content" :"Hello my friend 1"
    }
}

###Create Comment Has Parent
POST {{host}}/v1/api/comments HTTP/1.1
content-type: application/json

{
  "comment": 
    {
    "post_id" : "e4a448b6-278b-4a41-a936-9e2003fcee71",
    "user_id" :"526c0b00-677d-11ee-8390-0242ac150004",
    //"reply_to_id" : 1,
    "content" :"Hello 3",
    "parent_comment_id" : "174be2cd-ed9a-4534-89f5-a982944aac84"
    }
}

###Update Comment
PUT {{host}}/v1/api/comments/3de6407d-d10b-4cf7-a4ae-267253a47335 HTTP/1.1
content-type: application/json

{
  "comment": 
    {
      "content" :"Reply comment"
    }
  
}

###Get Comment By PostID
GET {{host}}/v1/api/posts/e4a448b6-278b-4a41-a936-9e2003fcee71/comments HTTP/1.1
content-type: application/json

{}

###Get Comment
GET {{host}}/v1/api/comments/852daf12-7676-46aa-aa14-053dc9ee84aa HTTP/1.1
content-type: application/json

{}

###Delete Comment
DELETE  {{host}}/v1/api/comments/852daf12-7676-46aa-aa14-053dc9ee84aa HTTP/1.1
content-type: application/json

{}