version: "3"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
    healthcheck:
      # test: ["CMD", "pg_isready"]
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - microservices-network
  redis:
    image: redis
    container_name: go-microservices-redis
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=password
      - REDIS_REPLICATION_mode=master
    ports:
      - "6379:6379"
    networks:
      - microservices-network
  redisinsight:
    image: redislabs/redisinsight
    container_name: go-microservices-redisinsight
    restart: unless-stopped
    volumes:
      - redis_data:/var/lib/redis
    ports:
      - "8001:8001"
    networks:
      - microservices-network
  proxy:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-proxy
    image: go-microservices-proxy
    environment:
      APP_NAME: 'proxy-service in docker'
      GRPC_GROUP_HOST: 'group'
      GRPC_GROUP_PORT: 5001
      GRPC_POST_HOST: 'post'
      GRPC_POST_PORT: 5002
      GRPC_COMMENT_HOST: 'comment'
      GRPC_COMMENT_PORT: 5003
      GRPC_LIKE_HOST: 'like'
      GRPC_LIKE_PORT: 5004
      GRPC_UPLOAD_HOST: 'upload'
      GRPC_UPLOAD_PORT: 5006
    ports:
      - 5000:5000
    depends_on:
      - group
      - post
      - comment
      - like
      - upload
    networks:
      - microservices-network
  group:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-group
    image: go-microservices-group
    environment:
      APP_NAME: 'group-service in docker'
      IN_DOCKER: "true"
      PG_URL: postgres://postgres:P@ssw0rd@postgres:5432/postgres
      PG_DSN_URL: host=postgres user=postgres password=P@ssw0rd dbname=postgres sslmode=disable
    ports:
      - 5001:5001
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - microservices-network
  post:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-post
    image: go-microservices-post
    environment:
      APP_NAME: 'post-service in docker'
      IN_DOCKER: "true"
      PG_URL: postgres://postgres:P@ssw0rd@postgres:5432/postgres
      PG_DSN_URL: host=postgres user=postgres password=P@ssw0rd dbname=postgres sslmode=disable
      LIKE_CLIENT_URL: like:5004
      COMMENT_CLIENT_URL: comment:5003
      UPLOAD_CLIENT_URL: upload:5006
    ports:
      - 5002:5002
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - microservices-network
  comment:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-comment
    image: go-microservices-comment
    environment:
      APP_NAME: 'comment-service in docker'
      IN_DOCKER: "true"
      PG_URL: postgres://postgres:P@ssw0rd@postgres:5432/postgres
      PG_DSN_URL: host=postgres user=postgres password=P@ssw0rd dbname=postgres sslmode=disable
      LIKE_CLIENT_URL: like:5004
    ports:
      - 5003:5003
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - microservices-network
  like:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-like
    image: go-microservices-like
    environment:
      APP_NAME: 'like-service in docker'
      IN_DOCKER: "true"
      PG_URL: postgres://postgres:P@ssw0rd@postgres:5432/postgres
      PG_DSN_URL: host=postgres user=postgres password=P@ssw0rd dbname=postgres sslmode=disable
    ports:
      - 5004:5004
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - microservices-network
  upload:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-upload
    image: go-microservices-upload
    env_file:
      - .env
    environment:
      APP_NAME: 'upload-service in docker'
      IN_DOCKER: "true"
      PG_URL: postgres://postgres:P@ssw0rd@postgres:5432/postgres
      PG_DSN_URL: host=postgres user=postgres password=P@ssw0rd dbname=postgres sslmode=disable
    ports:
      - 5005:5005
      - 5006:5006
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - microservices-network
  # web:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile-web
  #   image: go-microservices-web
  #   environment:
  #     REVERSE_PROXY_URL: http://localhost:5000
  #     WEB_PORT: 8888
  #   ports:
  #     - 8888:8888
  #   depends_on:
  #     - proxy
  #   networks:
  #     - microservices-network
volumes:
  postgres_data: {}
  redis_data: {}
networks:
  microservices-network:
