version: "3"

services:
  pg-master:
    build:
      context: .
      dockerfile: ./docker/pg-master/Dockerfile
    image: go-microservices-pg-master
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_MASTER=pg_slave
      # - PG_STANDBY=true #enable if switch to standby
      # - PG_REWIND=true #enable if need sync WAL
      - PG_REP_USER=rep_postgres
      - PG_REP_PASSWORD=123456789
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
    ports:
      - 5432:5432
    volumes:
      - mdata:/var/lib/postgresql/data
    networks:
      - microservices-network
  pg-slave:
    build:
      context: .
      dockerfile: ./docker/pg-slave/Dockerfile
    image: go-microservices-pg-slave
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456789
      - POSTGRES_DB=postgres
      - POSTGRES_MASTER=pg_master
      - PG_STANDBY=true
      - PG_REP_USER=rep_postgres
      - PG_REP_PASSWORD=123456789
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
    ports:
      - 5433:5432
    volumes:
      - sdata:/var/lib/postgresql/data
    depends_on:
      - pg-master
    networks:
      - microservices-network

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices-network
volumes:
  mdata:
  sdata:
networks:
  microservices-network:
