version: "3"

services:
  proxy:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-proxy
    image: mcs-proxy
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_NAME: 'proxy-service in docker'
      IN_DOCKER: "true"
      PG_URL: postgres://postgres:123456@postgres-master/postgres?sslmode=disable
      PG_REP_URL: postgres://postgres:123456@postgres-slave:5432/postgres?sslmode=disable
      GRPC_GROUP_HOST: 'group'
      GRPC_GROUP_PORT: 5001
      GRPC_POST_HOST: 'post'
      GRPC_POST_PORT: 5002
      GRPC_COMMENT_HOST: 'comment'
      GRPC_COMMENT_PORT: 5003
      GRPC_LIKE_HOST: 'like'
      GRPC_LIKE_PORT: 5004
      GRPC_UPLOAD_HOST: 'upload'
      GRPC_UPLOAD_PORT: 5006
      GRPC_AUTH_HOST: 'auth'
      GRPC_AUTH_PORT: 5007
      GRPC_SEARCH_HOST: 'search'
      GRPC_SEARCH_PORT: 5008
    ports:
      - 5000:5000
    depends_on:
      - group
      - post
      - comment
      - like
      - upload
      - auth
    networks:
      - mcs-network
  group:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-group
    image: mcs-group
    restart: unless-stopped
    environment:
      APP_NAME: 'group-service in docker'
      IN_DOCKER: "true"
      PG_URL: postgres://postgres:123456@postgres-master:5432/postgres?sslmode=disable
      PG_REP_URL: postgres://postgres:123456@postgres-slave:5432/postgres?sslmode=disable
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      AUTH_CLIENT_URL: auth:5007
    ports:
      - 5001:5001
    depends_on:
      - post
    networks:
      - mcs-network
  post:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-post
    image: mcs-post
    restart: unless-stopped
    environment:
      APP_NAME: 'post-service in docker'
      IN_DOCKER: "true"
      PG_URL: postgres://postgres:123456@postgres-master:5432/postgres?sslmode=disable
      PG_REP_URL: postgres://postgres:123456@postgres-slave:5432/postgres?sslmode=disable
      GROUP_CLIENT_URL: group:5001
      LIKE_CLIENT_URL: like:5004
      COMMENT_CLIENT_URL: comment:5003
      UPLOAD_CLIENT_URL: upload:5006
      AUTH_CLIENT_URL: auth:5007
    ports:
      - 5002:5002
    depends_on:
      - comment
    networks:
      - mcs-network
  comment:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-comment
    image: mcs-comment
    restart: unless-stopped
    environment:
      APP_NAME: 'comment-service in docker'
      IN_DOCKER: "true"
      PG_URL: postgres://postgres:123456@postgres-master:5432/postgres?sslmode=disable
      PG_REP_URL: postgres://postgres:123456@postgres-slave:5432/postgres?sslmode=disable
      LIKE_CLIENT_URL: like:5004
      UPLOAD_CLIENT_URL: upload:5006
      AUTH_CLIENT_URL: auth:5007
    ports:
      - 5003:5003
    depends_on:
      - like
    networks:
      - mcs-network
  like:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-like
    image: mcs-like
    restart: unless-stopped
    environment:
      APP_NAME: 'like-service in docker'
      IN_DOCKER: "true"
      PG_URL: postgres://postgres:123456@postgres-master:5432/postgres?sslmode=disable
      PG_REP_URL: postgres://postgres:123456@postgres-slave:5432/postgres?sslmode=disable
    ports:
      - 5004:5004
    depends_on:
      - upload
    networks:
      - mcs-network
  upload:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-upload
    image: mcs-upload
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_NAME: 'upload-service in docker'
      IN_DOCKER: "true"
      PG_URL: postgres://postgres:123456@postgres-master:5432/postgres?sslmode=disable
      PG_REP_URL: postgres://postgres:123456@postgres-slave:5432/postgres?sslmode=disable
    ports:
      - 5005:5005
      - 5006:5006
    depends_on:
      - auth
    networks:
      - mcs-network
  auth:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-auth
    image: mcs-auth
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_NAME: 'auth-service in docker'
      IN_DOCKER: "true"
      PG_URL: postgres://postgres:123456@postgres-master:5432/postgres?sslmode=disable
      PG_REP_URL: postgres://postgres:123456@postgres-slave:5432/postgres?sslmode=disable
      UPLOAD_CLIENT_URL: upload:5006
      GROUP_CLIENT_URL: group:5001
    depends_on:
      - search
    ports:
      - 5007:5007
    networks:
      - mcs-network
  search:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-search
    image: mcs-search
    restart: unless-stopped
    env_file:
      - .env
    environment:
      APP_NAME: 'search-service in docker'
      IN_DOCKER: "true"
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - 5008:5008
    networks:
      - mcs-network
  # fontend:
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile-web
  #   image: mcs-web
  #   environment:
  #     REVERSE_PROXY_URL: http://localhost:5000
  #     WEB_PORT: 8888
  #   ports:
  #     - 8888:8888
  #   depends_on:
  #     - proxy
  #   networks:
  #     - mcs-network
networks:
  mcs-network:
    name: mcs-network
    external: true
