version: "3"

services:
  postgres:
    image: postgres:14-alpine
    container_name: mcs-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P@ssw0rd
    healthcheck:
      # test: ["CMD", "pg_isready"]
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices-network
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: mcs-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - microservices-network
  redis:
    image: redis
    container_name: mcs-redis
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=password
      - REDIS_REPLICATION_mode=master
    ports:
      - 6379:6379
    networks:
      - microservices-network
  redisinsight:
    image: redislabs/redisinsight
    container_name: mcs-redisinsight
    restart: unless-stopped
    volumes:
      - redis_data:/var/lib/redis
    ports:
      - 8002:8001
    networks:
      - microservices-network
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
  #   container_name: mcs-elasticsearch
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - "9200:9200"
  #   networks:
  #     - microservices-network
volumes:
  postgres_data: {}
  redis_data: {}

networks:
    microservices-network:
      driver: bridge
      name: microservices-network