version: "3"

services:
  postgres-master:
    build: ./docker/pg-master
    image: postgres-master
    container_name: mcs-postgres-master
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
      - POSTGRES_MASTER=postgres-slave
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=123456
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
    ports:
      - 5445:5432
    depends_on:
      - postgres-slave
    volumes:
      - pgm-data:/var/lib/postgresql/data
    networks:
      - mcs-network
  postgres-slave:
    build: ./docker/pg-slave
    image: postgres-slave
    container_name: mcs-postgres-slave
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=postgres
      - POSTGRES_MASTER=postgres-master
      - PG_STANDBY=true
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=123456
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
    ports:
      - 5446:5432
    
    volumes:
      - pgs-data:/var/lib/postgresql/data
    networks:
      - mcs-network
  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: mcs-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mcs-network
  redis:
    image: redis
    container_name: mcs-redis
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_PASSWORD=password
      - REDIS_REPLICATION_mode=master
    ports:
      - 6379:6379
    networks:
      - mcs-network
  redisinsight:
    image: redislabs/redisinsight:2.66
    container_name: mcs-redisinsight
    restart: unless-stopped
    volumes:
      - ./env/data/redis-insight:/data
    depends_on:
      - redis
    ports:
      - 5540:5540
    networks:
      - mcs-network
  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: mcs-meilisearch
    restart: unless-stopped
    environment:
      - MEILI_MASTER_KEY=${ML_API_KEY:-ms}
    volumes:
      - mls_data:/data.ms
    ports:
      - "7700:7700" # Change ports if needed
    networks:
      - mcs-network
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: mcs-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_SERVERS: zookeeper:2888:3888
    ports:
      - "2181:2181"
    networks:
      - mcs-network
  kafka1:
    image: confluentinc/cp-kafka:7.9.0
    container_name: mcs-kafka1
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
    networks:
      - mcs-network
  debezium:
    image: debezium/connect:2.7.3.Final
    container_name: mcs-debezium
    depends_on:
      - kafka1
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka1:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      STATUS_STORAGE_TOPIC: connect_statuses
      OFFSET_STORAGE_TOPIC: connect_offsets
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      ENABLE_DEBEZIUM_SCRIPTING: "true"
    networks:
      - mcs-network
  debezium-ui:
    image: debezium/debezium-ui:latest
    container_name: debezium-ui
    depends_on:
      - debezium
    ports:
      - "8080:8080"
    environment:
      KAFKA_CONNECT_URIS: http://debezium:8083
    networks:
      - mcs-network
  schema-registry:
    image: confluentinc/cp-schema-registry:7.9.0
    container_name: mcs-schema-registry
    depends_on:
      - kafka1
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka1:29092
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: mcs-kafdrop
    depends_on:
      - kafka1
    ports:
      - "9123:9123"
    environment:
      SERVER_PORT: 9123
      MANAGEMENT_SERVER_PORT: 9123
      KAFKA_BROKERCONNECT: kafka-broker-1:29092 
    networks:
      - mcs-network
  elasticsearch:
    container_name: mcs-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.25
    restart: always
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx256m -Xms256m
    volumes:
      - ./env/elk/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - mcs-network
  kibana:
    container_name: mcs-kibana
    image: docker.elastic.co/kibana/kibana:7.17.25
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    volumes:
      - ./env/elk/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - mcs-network
  logstash:
    image: logstash:7.17.25
    container_name: mcs-logstash
    volumes:
      - ./env/elk/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./env/elk/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
      - "5033:5000/tcp"
      - "5022:5000/udp"
      - "9600:9600"
    environment:
      - LS_JAVA_OPTS=-Xmx256m -Xms256m
    depends_on:
      - elasticsearch
    networks:
      - mcs-network
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.25
    container_name: mcs-filebeat
    user: root
    volumes:
      - ./env/elk/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    depends_on:
      - elasticsearch
    networks:
      - mcs-network
  prometheus:
    image: prom/prometheus
    container_name: mcs-prometheus
    restart: unless-stopped
    volumes:
      - ./env/prometheus/prometheus.yml/:/etc/prometheus/prometheus.yml
      - ./env/data/prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - mcs-network
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    container_name: mcs-grafana
    restart: unless-stopped
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      #enable logger
      - GF_LOG_MODE=console file
      - GF_LOG_FILTERS=alerting.notifier.slack:debug alermanager:debug ngalert:debug
    volumes:
      - ./env/data/grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - mcs-network
  node-exporter:
    image: prom/node-exporter
    container_name: mcs-node-exporter
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    networks:
      - mcs-network
  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: mcs-postgres-exporter
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgres://postgres:123456@postgres-master:5432/postgres?sslmode=disable"
    depends_on:
      - postgres-master
    networks:
      - mcs-network
  redis-exporter:
    image: oliver006/redis_exporter
    container_name: mcs-redis-exporter
    command: -redis.addr redis://redis:6379
    ports:
      - "9121:9121"
    depends_on:
      - redis
    networks:
      - mcs-network
  elasticsearch_exporter:
    image: prometheuscommunity/elasticsearch-exporter
    container_name: mcs-elasticsearch-exporter
    command:
     - '--es.uri=http://elasticsearch:9200'
    restart: always
    depends_on:
      - elasticsearch
    ports:
      - "9114:9114"
    networks:
      - mcs-network
volumes:
  pgm-data: {}
  pgs-data: {}
  redis_data: {}
  mls_data: {}

networks:
    mcs-network:
      driver: bridge
      name: mcs-network



  


