// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: query.sql

package postgresql

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const create = `-- name: Create :one
INSERT INTO
    "group".groups (
        id,
        status,
        name,
        description,
        user_id,
        deleted_at
    )
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, user_id, name, description, status, created_at, updated_at, deleted_at
`

type CreateParams struct {
	ID          uuid.UUID    `json:"id"`
	Status      int32        `json:"status"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	UserID      uuid.UUID    `json:"user_id"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (GroupGroup, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.Status,
		arg.Name,
		arg.Description,
		arg.UserID,
		arg.DeletedAt,
	)
	var i GroupGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM "group".groups WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const get = `-- name: Get :one
SELECT id, user_id, name, description, status, created_at, updated_at, deleted_at FROM "group".groups WHERE id = $1
`

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (GroupGroup, error) {
	row := q.db.QueryRowContext(ctx, get, id)
	var i GroupGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const update = `-- name: Update :one
UPDATE "group".groups 
SET
    name = $2 ,
    description = $3,
    status = $4,
    deleted_at = $5
WHERE id = $1 RETURNING id, user_id, name, description, status, created_at, updated_at, deleted_at
`

type UpdateParams struct {
	ID          uuid.UUID    `json:"id"`
	Name        string       `json:"name"`
	Description string       `json:"description"`
	Status      int32        `json:"status"`
	DeletedAt   sql.NullTime `json:"deleted_at"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (GroupGroup, error) {
	row := q.db.QueryRowContext(ctx, update,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.DeletedAt,
	)
	var i GroupGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
