// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package postgresql

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countGroupMembers = `-- name: CountGroupMembers :one
SELECT count(*) FROM "group".group_members WHERE group_id = $1
`

func (q *Queries) CountGroupMembers(ctx context.Context, groupID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGroupMembers, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const create = `-- name: Create :one
INSERT INTO
    "group".groups (
        id,
        status,
        name,
        description,
        user_id
    )
VALUES ($1, $2, $3, $4, $5) RETURNING id, user_id, name, description, status, profile_url, created_at, updated_at
`

type CreateParams struct {
	ID          uuid.UUID `json:"id"`
	Status      int32     `json:"status"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	UserID      uuid.UUID `json:"user_id"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (GroupGroup, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.Status,
		arg.Name,
		arg.Description,
		arg.UserID,
	)
	var i GroupGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.ProfileUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroupMember = `-- name: CreateGroupMember :one
INSERT INTO "group".group_members
(
    id,
    group_id,
    user_id,
    role
)
VALUES ($1,$2,$3,$4) RETURNING id, group_id, user_id, role, status, created_at, updated_at
`

type CreateGroupMemberParams struct {
	ID      uuid.UUID `json:"id"`
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
	Role    int32     `json:"role"`
}

func (q *Queries) CreateGroupMember(ctx context.Context, arg CreateGroupMemberParams) (GroupGroupMember, error) {
	row := q.db.QueryRowContext(ctx, createGroupMember,
		arg.ID,
		arg.GroupID,
		arg.UserID,
		arg.Role,
	)
	var i GroupGroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createGroupMembers = `-- name: CreateGroupMembers :many
INSERT INTO "group".group_members
(
    id,
    group_id,
    user_id,
    role
)
VALUES ($1,$2,$3,$4) RETURNING id, group_id, user_id, role, status, created_at, updated_at
`

type CreateGroupMembersParams struct {
	ID      uuid.UUID `json:"id"`
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
	Role    int32     `json:"role"`
}

func (q *Queries) CreateGroupMembers(ctx context.Context, arg CreateGroupMembersParams) ([]GroupGroupMember, error) {
	rows, err := q.db.QueryContext(ctx, createGroupMembers,
		arg.ID,
		arg.GroupID,
		arg.UserID,
		arg.Role,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupGroupMember
	for rows.Next() {
		var i GroupGroupMember
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const delete = `-- name: Delete :exec
DELETE FROM "group".groups WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const deleteGroupMember = `-- name: DeleteGroupMember :exec
DELETE FROM "group".group_members WHERE id = $1
`

func (q *Queries) DeleteGroupMember(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGroupMember, id)
	return err
}

const deleteGroupMembersByGroupId = `-- name: DeleteGroupMembersByGroupId :exec
DELETE FROM "group".group_members WHERE group_id = $1
`

func (q *Queries) DeleteGroupMembersByGroupId(ctx context.Context, groupID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteGroupMembersByGroupId, groupID)
	return err
}

const get = `-- name: Get :one
SELECT id, user_id, name, description, status, profile_url, created_at, updated_at FROM "group".groups WHERE id = $1
`

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (GroupGroup, error) {
	row := q.db.QueryRowContext(ctx, get, id)
	var i GroupGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.ProfileUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupIdsByUserId = `-- name: GetGroupIdsByUserId :many
SELECT gm.group_id
FROM "group".group_members as gm
WHERE user_id = $1
`

func (q *Queries) GetGroupIdsByUserId(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getGroupIdsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var group_id uuid.UUID
		if err := rows.Scan(&group_id); err != nil {
			return nil, err
		}
		items = append(items, group_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupMembers = `-- name: GetGroupMembers :many
SELECT id, group_id, user_id, role, status, created_at, updated_at FROM "group".group_members WHERE group_id = $1
`

func (q *Queries) GetGroupMembers(ctx context.Context, groupID uuid.UUID) ([]GroupGroupMember, error) {
	rows, err := q.db.QueryContext(ctx, getGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupGroupMember
	for rows.Next() {
		var i GroupGroupMember
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.UserID,
			&i.Role,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGroupsByUserId = `-- name: GetGroupsByUserId :many
SELECT g.id, g.user_id, g.name, g.description, g.status, g.profile_url, g.created_at, g.updated_at
FROM "group".groups AS g
INNER JOIN "group".group_members AS gm ON g.id = gm.group_id
WHERE gm.user_id = $1 LIMIT $2 OFFSET $3
`

type GetGroupsByUserIdParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetGroupsByUserId(ctx context.Context, arg GetGroupsByUserIdParams) ([]GroupGroup, error) {
	rows, err := q.db.QueryContext(ctx, getGroupsByUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GroupGroup
	for rows.Next() {
		var i GroupGroup
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.ProfileUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRoleOfGroupMember = `-- name: GetRoleOfGroupMember :one
SELECT role FROM "group".group_members WHERE group_id = $1 AND user_id = $2
`

type GetRoleOfGroupMemberParams struct {
	GroupID uuid.UUID `json:"group_id"`
	UserID  uuid.UUID `json:"user_id"`
}

func (q *Queries) GetRoleOfGroupMember(ctx context.Context, arg GetRoleOfGroupMemberParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, getRoleOfGroupMember, arg.GroupID, arg.UserID)
	var role int32
	err := row.Scan(&role)
	return role, err
}

const getWithUnscoped = `-- name: GetWithUnscoped :one
SELECT id, user_id, name, description, status, profile_url, created_at, updated_at FROM "group".groups WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) GetWithUnscoped(ctx context.Context, id uuid.UUID) (GroupGroup, error) {
	row := q.db.QueryRowContext(ctx, getWithUnscoped, id)
	var i GroupGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.ProfileUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const update = `-- name: Update :one
UPDATE "group".groups 
SET
    name = COALESCE($1,name),
    description = COALESCE($2,description),
    status = COALESCE($3,status),
    profile_url = COALESCE($4,profile_url)
WHERE id = $5 RETURNING id, user_id, name, description, status, profile_url, created_at, updated_at
`

type UpdateParams struct {
	Name        sql.NullString `json:"name"`
	Description sql.NullString `json:"description"`
	Status      sql.NullInt32  `json:"status"`
	ProfileUrl  sql.NullString `json:"profile_url"`
	ID          uuid.UUID      `json:"id"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (GroupGroup, error) {
	row := q.db.QueryRowContext(ctx, update,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.ProfileUrl,
		arg.ID,
	)
	var i GroupGroup
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.ProfileUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateGroupMember = `-- name: UpdateGroupMember :one
UPDATE "group".group_members
SET
    role = COALESCE($1,role)
WHERE id = $2 RETURNING id, group_id, user_id, role, status, created_at, updated_at
`

type UpdateGroupMemberParams struct {
	Role sql.NullInt32 `json:"role"`
	ID   uuid.UUID     `json:"id"`
}

func (q *Queries) UpdateGroupMember(ctx context.Context, arg UpdateGroupMemberParams) (GroupGroupMember, error) {
	row := q.db.QueryRowContext(ctx, updateGroupMember, arg.Role, arg.ID)
	var i GroupGroupMember
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
