// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package postgresql

import (
	"time"

	"github.com/google/uuid"
)

type PostPost struct {
	ID        uuid.UUID     `json:"id"`
	UserID    uuid.UUID     `json:"user_id"`
	GroupID   uuid.NullUUID `json:"group_id"`
	Content   string        `json:"content"`
	BgContent string        `json:"bg_content"`
	Status    int32         `json:"status"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}
