// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: query.sql

package postgresql

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const count = `-- name: Count :one
SELECT COUNT(*) FROM post.posts
`

func (q *Queries) Count(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, count)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const create = `-- name: Create :one
INSERT INTO
    post.posts (
        id,
        status,
        title,
        content,
        user_id,
        group_id,
        deleted_at
    )
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, user_id, group_id, title, content, status, created_at, updated_at, deleted_at
`

type CreateParams struct {
	ID        uuid.UUID     `json:"id"`
	Status    int32         `json:"status"`
	Title     string        `json:"title"`
	Content   string        `json:"content"`
	UserID    uuid.UUID     `json:"user_id"`
	GroupID   uuid.NullUUID `json:"group_id"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (PostPost, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.Status,
		arg.Title,
		arg.Content,
		arg.UserID,
		arg.GroupID,
		arg.DeletedAt,
	)
	var i PostPost
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM post.posts WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const get = `-- name: Get :one
SELECT id, user_id, group_id, title, content, status, created_at, updated_at, deleted_at FROM post.posts WHERE id = $1
`

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (PostPost, error) {
	row := q.db.QueryRowContext(ctx, get, id)
	var i PostPost
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWithUnscoped = `-- name: GetWithUnscoped :one
SELECT id, user_id, group_id, title, content, status, created_at, updated_at, deleted_at FROM post.posts 
WHERE id = $1 AND deleted_at IS NOT NULL
`

func (q *Queries) GetWithUnscoped(ctx context.Context, id uuid.UUID) (PostPost, error) {
	row := q.db.QueryRowContext(ctx, getWithUnscoped, id)
	var i PostPost
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const list = `-- name: List :many
SELECT id, user_id, group_id, title, content, status, created_at, updated_at, deleted_at FROM post.posts OFFSET $1 LIMIT $2
`

type ListParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) List(ctx context.Context, arg ListParams) ([]PostPost, error) {
	rows, err := q.db.QueryContext(ctx, list, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostPost
	for rows.Next() {
		var i PostPost
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :one
UPDATE post.posts 
SET
    title = $2 ,
    content = $3,
    status = $4,
    deleted_at = $5
WHERE id = $1 RETURNING id, user_id, group_id, title, content, status, created_at, updated_at, deleted_at
`

type UpdateParams struct {
	ID        uuid.UUID    `json:"id"`
	Title     string       `json:"title"`
	Content   string       `json:"content"`
	Status    int32        `json:"status"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (PostPost, error) {
	row := q.db.QueryRowContext(ctx, update,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Status,
		arg.DeletedAt,
	)
	var i PostPost
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
