// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package postgresql

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const create = `-- name: Create :one
INSERT INTO
    post.posts (
        id,
        status,
        title,
        content,
        user_id,
        group_id
    )
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, user_id, group_id, title, content, status, created_at, updated_at
`

type CreateParams struct {
	ID      uuid.UUID     `json:"id"`
	Status  int32         `json:"status"`
	Title   string        `json:"title"`
	Content string        `json:"content"`
	UserID  uuid.UUID     `json:"user_id"`
	GroupID uuid.NullUUID `json:"group_id"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (PostPost, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.Status,
		arg.Title,
		arg.Content,
		arg.UserID,
		arg.GroupID,
	)
	var i PostPost
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM post.posts WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const get = `-- name: Get :one
SELECT id, user_id, group_id, title, content, status, created_at, updated_at FROM post.posts WHERE id = $1
`

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (PostPost, error) {
	row := q.db.QueryRowContext(ctx, get, id)
	var i PostPost
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getByFeed = `-- name: GetByFeed :many
SELECT id, user_id, group_id, title, content, status, created_at, updated_at
FROM post.posts
WHERE user_id = ANY($1::uuid[])
   OR group_id = ANY($2::uuid[])
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type GetByFeedParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Column2 []uuid.UUID `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) GetByFeed(ctx context.Context, arg GetByFeedParams) ([]PostPost, error) {
	rows, err := q.db.QueryContext(ctx, getByFeed,
		pq.Array(arg.Column1),
		pq.Array(arg.Column2),
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostPost
	for rows.Next() {
		var i PostPost
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByGroupId = `-- name: GetByGroupId :many
SELECT id, user_id, group_id, title, content, status, created_at, updated_at FROM post.posts WHERE group_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type GetByGroupIdParams struct {
	GroupID uuid.NullUUID `json:"group_id"`
	Limit   int32         `json:"limit"`
	Offset  int32         `json:"offset"`
}

func (q *Queries) GetByGroupId(ctx context.Context, arg GetByGroupIdParams) ([]PostPost, error) {
	rows, err := q.db.QueryContext(ctx, getByGroupId, arg.GroupID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostPost
	for rows.Next() {
		var i PostPost
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByUserId = `-- name: GetByUserId :many
SELECT id, user_id, group_id, title, content, status, created_at, updated_at FROM post.posts 
WHERE user_id = $1 AND group_id IS NULL ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type GetByUserIdParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetByUserId(ctx context.Context, arg GetByUserIdParams) ([]PostPost, error) {
	rows, err := q.db.QueryContext(ctx, getByUserId, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostPost
	for rows.Next() {
		var i PostPost
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :one
UPDATE post.posts 
SET
    title = COALESCE($1,title),
    content = COALESCE($2,content),
    status = COALESCE($3,status)
WHERE id = $4 RETURNING id, user_id, group_id, title, content, status, created_at, updated_at
`

type UpdateParams struct {
	Title   sql.NullString `json:"title"`
	Content sql.NullString `json:"content"`
	Status  sql.NullInt32  `json:"status"`
	ID      uuid.UUID      `json:"id"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (PostPost, error) {
	row := q.db.QueryRowContext(ctx, update,
		arg.Title,
		arg.Content,
		arg.Status,
		arg.ID,
	)
	var i PostPost
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
