// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: query.sql

package postgresql

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countPosts = `-- name: CountPosts :one
SELECT COUNT(*) FROM post.posts
`

func (q *Queries) CountPosts(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPosts)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPost = `-- name: CreatePost :one
INSERT INTO
    post.posts (
        id,
        status,
        title,
        content,
        user_id,
        group_id,
        deleted_at
    )
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, user_id, group_id, title, content, status, created_at, updated_at, deleted_at
`

type CreatePostParams struct {
	ID        uuid.UUID     `json:"id"`
	Status    int32         `json:"status"`
	Title     string        `json:"title"`
	Content   string        `json:"content"`
	UserID    uuid.UUID     `json:"user_id"`
	GroupID   uuid.NullUUID `json:"group_id"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (PostPost, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.Status,
		arg.Title,
		arg.Content,
		arg.UserID,
		arg.GroupID,
		arg.DeletedAt,
	)
	var i PostPost
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePost = `-- name: DeletePost :exec
DELETE FROM post.posts WHERE id = $1
`

func (q *Queries) DeletePost(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePost, id)
	return err
}

const getPost = `-- name: GetPost :one
SELECT id, user_id, group_id, title, content, status, created_at, updated_at, deleted_at FROM post.posts WHERE id = $1
`

func (q *Queries) GetPost(ctx context.Context, id uuid.UUID) (PostPost, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i PostPost
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPosts = `-- name: ListPosts :many
SELECT id, user_id, group_id, title, content, status, created_at, updated_at, deleted_at FROM post.posts OFFSET $1 LIMIT $2
`

type ListPostsParams struct {
	Offset int32 `json:"offset"`
	Limit  int32 `json:"limit"`
}

func (q *Queries) ListPosts(ctx context.Context, arg ListPostsParams) ([]PostPost, error) {
	rows, err := q.db.QueryContext(ctx, listPosts, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostPost
	for rows.Next() {
		var i PostPost
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.GroupID,
			&i.Title,
			&i.Content,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE post.posts 
SET
    title = $2 ,
    content = $3,
    status = $4,
    deleted_at = $5
WHERE id = $1 RETURNING id, user_id, group_id, title, content, status, created_at, updated_at, deleted_at
`

type UpdatePostParams struct {
	ID        uuid.UUID    `json:"id"`
	Title     string       `json:"title"`
	Content   string       `json:"content"`
	Status    int32        `json:"status"`
	DeletedAt sql.NullTime `json:"deleted_at"`
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (PostPost, error) {
	row := q.db.QueryRowContext(ctx, updatePost,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Status,
		arg.DeletedAt,
	)
	var i PostPost
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePostWithUnscoped = `-- name: UpdatePostWithUnscoped :one
UPDATE post.posts 
SET 
    title = $2, 
    content = $3, 
    status = $4
WHERE id = $1 AND deleted_at IS NOT NULL RETURNING id, user_id, group_id, title, content, status, created_at, updated_at, deleted_at
`

type UpdatePostWithUnscopedParams struct {
	ID      uuid.UUID `json:"id"`
	Title   string    `json:"title"`
	Content string    `json:"content"`
	Status  int32     `json:"status"`
}

func (q *Queries) UpdatePostWithUnscoped(ctx context.Context, arg UpdatePostWithUnscopedParams) (PostPost, error) {
	row := q.db.QueryRowContext(ctx, updatePostWithUnscoped,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Status,
	)
	var i PostPost
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.GroupID,
		&i.Title,
		&i.Content,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
