// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/dinhcanh303/go-microservices/cmd/notification/config"
	"github.com/dinhcanh303/go-microservices/internal/notification/app/router"
	"github.com/dinhcanh303/go-microservices/internal/notification/eventhandlers"
	"github.com/dinhcanh303/go-microservices/internal/notification/infras/repo"
	"github.com/dinhcanh303/go-microservices/internal/notification/usecases/notifications"
	"github.com/dinhcanh303/go-microservices/pkg/config"
	"github.com/dinhcanh303/go-microservices/pkg/postgres"
	"github.com/dinhcanh303/go-microservices/pkg/rabbitmq"
	"github.com/dinhcanh303/go-microservices/pkg/rabbitmq/consumer"
	"github.com/dinhcanh303/go-microservices/pkg/redis"
	"github.com/rabbitmq/amqp091-go"
	"google.golang.org/grpc"
	postgres2 "gorm.io/driver/postgres"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, cfg2 *configs.Redis, dbConnStr postgres.DBConnString, dbReadConnStr postgres.DBConnReadString, rabbitMQConnStr rabbitmq.RabbitMQConnStr, grpcServer *grpc.Server) (*App, func(), error) {
	db, err := dbEngineFunc(dbConnStr, dbReadConnStr)
	if err != nil {
		return nil, nil, err
	}
	connection, cleanup, err := rabbitMQFunc(rabbitMQConnStr)
	if err != nil {
		return nil, nil, err
	}
	notificationRepo := repo.NewNotificationRepo(db)
	redisEngine, cleanup2, err := redisEngineFunc(cfg2)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	useCase := notifications.NewService(notificationRepo, redisEngine)
	notiServiceServer := router.NewNotiGRPCServer(grpcServer, useCase)
	eventConsumer, err := consumer.NewConsumer(connection)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	notificationEventHandler := eventhandlers.NewEventHandlers(useCase)
	app := New(cfg, db, connection, notiServiceServer, eventConsumer, notificationEventHandler)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func dbEngineFunc(url postgres.DBConnString, urlRead postgres.DBConnReadString) (*gorm.DB, error) {
	db, err := gorm.Open(postgres2.Open(string(url)), &gorm.Config{})
	if err != nil {
		return nil, err
	}
	return db, nil
}

func redisEngineFunc(config2 *configs.Redis) (redis.RedisEngine, func(), error) {
	redis2, err := redis.NewRedisClient(config2)
	if err != nil {
		return nil, nil, err
	}
	return redis2, func() {
		redis2.Close()
	}, nil
}

func rabbitMQFunc(url rabbitmq.RabbitMQConnStr) (*amqp091.Connection, func(), error) {
	conn, err := rabbitmq.NewRabbitMQConn(url)
	if err != nil {
		return nil, nil, err
	}
	return conn, func() { conn.Close() }, nil
}
