// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgresql

import (
	"time"

	"github.com/google/uuid"
)

type LikeLike struct {
	ID           uuid.UUID `json:"id"`
	Emoji        string    `json:"emoji"`
	LikeableType string    `json:"likeable_type"`
	LikeableID   uuid.UUID `json:"likeable_id"`
	UserID       uuid.UUID `json:"user_id"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}
