// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package postgresql

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const create = `-- name: Create :one
INSERT INTO 
    "like".likes (
        id,
		emoji,
		likeable_type,
		likeable_id,
		user_id
    )
VALUES ($1, $2, $3, $4, $5) RETURNING id, emoji, likeable_type, likeable_id, user_id, created_at, updated_at
`

type CreateParams struct {
	ID           uuid.UUID `json:"id"`
	Emoji        string    `json:"emoji"`
	LikeableType string    `json:"likeable_type"`
	LikeableID   uuid.UUID `json:"likeable_id"`
	UserID       uuid.UUID `json:"user_id"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (LikeLike, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.Emoji,
		arg.LikeableType,
		arg.LikeableID,
		arg.UserID,
	)
	var i LikeLike
	err := row.Scan(
		&i.ID,
		&i.Emoji,
		&i.LikeableType,
		&i.LikeableID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM "like".likes WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const getAllByType = `-- name: GetAllByType :many
SELECT id, emoji, likeable_type, likeable_id, user_id, created_at, updated_at FROM "like".likes WHERE likeable_type = $1
AND likeable_id = $2
`

type GetAllByTypeParams struct {
	LikeableType string    `json:"likeable_type"`
	LikeableID   uuid.UUID `json:"likeable_id"`
}

func (q *Queries) GetAllByType(ctx context.Context, arg GetAllByTypeParams) ([]LikeLike, error) {
	rows, err := q.db.QueryContext(ctx, getAllByType, arg.LikeableType, arg.LikeableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LikeLike
	for rows.Next() {
		var i LikeLike
		if err := rows.Scan(
			&i.ID,
			&i.Emoji,
			&i.LikeableType,
			&i.LikeableID,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLikesInfoByType = `-- name: GetLikesInfoByType :one
SELECT
    COUNT(*) FILTER (WHERE user_id = $1) AS your_like,
    COUNT(*) FILTER (WHERE user_id != $1) AS others_likes,
	COALESCE(MIN(CASE WHEN user_id = $1 THEN emoji END),'') AS your_liked_emoji,
	COALESCE(ARRAY_AGG(DISTINCT emoji ), '{}') AS others_liked_emojis
FROM "like".likes
WHERE likeable_type = $2 AND likeable_id = $3
LIMIT 1
`

type GetLikesInfoByTypeParams struct {
	UserID       uuid.UUID `json:"user_id"`
	LikeableType string    `json:"likeable_type"`
	LikeableID   uuid.UUID `json:"likeable_id"`
}

type GetLikesInfoByTypeRow struct {
	YourLike          int64       `json:"your_like"`
	OthersLikes       int64       `json:"others_likes"`
	YourLikedEmoji    interface{} `json:"your_liked_emoji"`
	OthersLikedEmojis interface{} `json:"others_liked_emojis"`
}

func (q *Queries) GetLikesInfoByType(ctx context.Context, arg GetLikesInfoByTypeParams) (GetLikesInfoByTypeRow, error) {
	row := q.db.QueryRowContext(ctx, getLikesInfoByType, arg.UserID, arg.LikeableType, arg.LikeableID)
	var i GetLikesInfoByTypeRow
	err := row.Scan(
		&i.YourLike,
		&i.OthersLikes,
		&i.YourLikedEmoji,
		&i.OthersLikedEmojis,
	)
	return i, err
}

const update = `-- name: Update :one
UPDATE "like".likes
SET
	emoji = COALESCE($1,emoji)
WHERE id = $2 RETURNING id, emoji, likeable_type, likeable_id, user_id, created_at, updated_at
`

type UpdateParams struct {
	Emoji sql.NullString `json:"emoji"`
	ID    uuid.UUID      `json:"id"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (LikeLike, error) {
	row := q.db.QueryRowContext(ctx, update, arg.Emoji, arg.ID)
	var i LikeLike
	err := row.Scan(
		&i.ID,
		&i.Emoji,
		&i.LikeableType,
		&i.LikeableID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
