// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/dinhcanh303/go-microservices/cmd/post/config"
	"github.com/dinhcanh303/go-microservices/internal/post/app/router"
	"github.com/dinhcanh303/go-microservices/internal/post/infras"
	grpc2 "github.com/dinhcanh303/go-microservices/internal/post/infras/grpc"
	"github.com/dinhcanh303/go-microservices/internal/post/infras/repo"
	"github.com/dinhcanh303/go-microservices/internal/post/usecases/posts"
	"github.com/dinhcanh303/go-microservices/pkg/config"
	"github.com/dinhcanh303/go-microservices/pkg/postgres"
	"github.com/dinhcanh303/go-microservices/pkg/rabbitmq"
	"github.com/dinhcanh303/go-microservices/pkg/rabbitmq/publisher"
	"github.com/dinhcanh303/go-microservices/pkg/redis"
	"github.com/rabbitmq/amqp091-go"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, cfg2 *configs.Redis, dbConnStr postgres.DBConnString, dbReadConnStr postgres.DBConnReadString, rabbitMQConnStr rabbitmq.RabbitMQConnStr, grpcServer *grpc.Server) (*App, func(), error) {
	dbEngine, cleanup, err := dbEngineFunc(dbConnStr, dbReadConnStr)
	if err != nil {
		return nil, nil, err
	}
	connection, cleanup2, err := rabbitMQFunc(rabbitMQConnStr)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	postRepo := repo.NewPostRepo(dbEngine)
	redisEngine, cleanup3, err := redisEngineFunc(cfg2)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	eventPublisher, err := publisher.NewPublisher(connection)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	notiEventPublisher := infras.NewNotiEventPublisher(eventPublisher)
	authDomainService, err := grpc2.NewGRPCAuthClient(cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	useCase := posts.NewUseCase(postRepo, redisEngine, notiEventPublisher, authDomainService)
	uploadDomainService, err := grpc2.NewGRPCUploadClient(cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	commentDomainService, err := grpc2.NewGRPCCommentClient(cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	likeDomainService, err := grpc2.NewGRPCLikeClient(cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	groupDomainService, err := grpc2.NewGRPCGroupClient(cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	postServiceServer := router.NewGRPCPostServer(grpcServer, cfg, useCase, uploadDomainService, commentDomainService, likeDomainService, groupDomainService, authDomainService)
	app := New(cfg, dbEngine, connection, useCase, eventPublisher, postServiceServer, commentDomainService, likeDomainService, uploadDomainService)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func dbEngineFunc(url postgres.DBConnString, urlRead postgres.DBConnReadString) (postgres.DBEngine, func(), error) {
	db, err := postgres.NewPostgresDB(url, urlRead)
	if err != nil {
		return nil, nil, err
	}
	return db, func() { db.Close() }, nil
}

func redisEngineFunc(config2 *configs.Redis) (redis.RedisEngine, func(), error) {
	redis2, err := redis.NewRedisClient(config2)
	if err != nil {
		return nil, nil, err
	}
	return redis2, func() {
		redis2.Close()
	}, nil
}

func rabbitMQFunc(url rabbitmq.RabbitMQConnStr) (*amqp091.Connection, func(), error) {
	conn, err := rabbitmq.NewRabbitMQConn(url)
	if err != nil {
		return nil, nil, err
	}
	return conn, func() { conn.Close() }, nil
}
