// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/dinhcanh303/go-microservices/cmd/post/config"
	"github.com/dinhcanh303/go-microservices/internal/post/app/router"
	grpc2 "github.com/dinhcanh303/go-microservices/internal/post/infras/grpc"
	"github.com/dinhcanh303/go-microservices/internal/post/infras/repo"
	"github.com/dinhcanh303/go-microservices/internal/post/usecases/posts"
	"github.com/dinhcanh303/go-microservices/pkg/postgres"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, dbConnStr postgres.DBConnString, grpcServer *grpc.Server) (*App, func(), error) {
	dbEngine, cleanup, err := dbEngineFunc(dbConnStr)
	if err != nil {
		return nil, nil, err
	}
	postRepo := repo.NewPostRepo(dbEngine)
	useCase := posts.NewUseCase(postRepo)
	uploadDomainService, err := grpc2.NewGRPCUploadClient(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	commentDomainService, err := grpc2.NewGRPCCommentClient(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	likeDomainService, err := grpc2.NewGRPCLikeClient(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	postServiceServer := router.NewGRPCPostServer(grpcServer, cfg, useCase, uploadDomainService, commentDomainService, likeDomainService)
	app := New(cfg, dbEngine, useCase, postServiceServer, commentDomainService, likeDomainService, uploadDomainService)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

func dbEngineFunc(url postgres.DBConnString) (postgres.DBEngine, func(), error) {
	db, err := postgres.NewPostgresDB(url)
	if err != nil {
		return nil, nil, err
	}
	return db, func() { db.Close() }, nil
}
