input {
  tcp {
    port => 5008
    codec => json_lines
  }
}

filter {}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    # index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
  }
}