

docker-compose: docker-compose-stop docker-compose-start
.PHONY: docker-compose

docker-compose-start:
	docker-compose up --build -d
.PHONY: docker-compose-start

docker-compose-stop:
	docker-compose down
.PHONY: docker-compose-stop