// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: noti/v1/noti.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NotiService_GetNotifications_FullMethodName         = "/noti.v1.NotiService/GetNotifications"
	NotiService_CountNotificationsUnread_FullMethodName = "/noti.v1.NotiService/CountNotificationsUnread"
	NotiService_ReadNotification_FullMethodName         = "/noti.v1.NotiService/ReadNotification"
)

// NotiServiceClient is the client API for NotiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotiServiceClient interface {
	GetNotifications(ctx context.Context, in *GetNotificationsRequest, opts ...grpc.CallOption) (*GetNotificationsResponse, error)
	CountNotificationsUnread(ctx context.Context, in *CountNotificationsUnreadRequest, opts ...grpc.CallOption) (*CountNotificationsUnreadResponse, error)
	ReadNotification(ctx context.Context, in *ReadNotificationRequest, opts ...grpc.CallOption) (*ReadNotificationResponse, error)
}

type notiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotiServiceClient(cc grpc.ClientConnInterface) NotiServiceClient {
	return &notiServiceClient{cc}
}

func (c *notiServiceClient) GetNotifications(ctx context.Context, in *GetNotificationsRequest, opts ...grpc.CallOption) (*GetNotificationsResponse, error) {
	out := new(GetNotificationsResponse)
	err := c.cc.Invoke(ctx, NotiService_GetNotifications_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notiServiceClient) CountNotificationsUnread(ctx context.Context, in *CountNotificationsUnreadRequest, opts ...grpc.CallOption) (*CountNotificationsUnreadResponse, error) {
	out := new(CountNotificationsUnreadResponse)
	err := c.cc.Invoke(ctx, NotiService_CountNotificationsUnread_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notiServiceClient) ReadNotification(ctx context.Context, in *ReadNotificationRequest, opts ...grpc.CallOption) (*ReadNotificationResponse, error) {
	out := new(ReadNotificationResponse)
	err := c.cc.Invoke(ctx, NotiService_ReadNotification_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotiServiceServer is the server API for NotiService service.
// All implementations must embed UnimplementedNotiServiceServer
// for forward compatibility
type NotiServiceServer interface {
	GetNotifications(context.Context, *GetNotificationsRequest) (*GetNotificationsResponse, error)
	CountNotificationsUnread(context.Context, *CountNotificationsUnreadRequest) (*CountNotificationsUnreadResponse, error)
	ReadNotification(context.Context, *ReadNotificationRequest) (*ReadNotificationResponse, error)
	mustEmbedUnimplementedNotiServiceServer()
}

// UnimplementedNotiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNotiServiceServer struct {
}

func (UnimplementedNotiServiceServer) GetNotifications(context.Context, *GetNotificationsRequest) (*GetNotificationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNotifications not implemented")
}
func (UnimplementedNotiServiceServer) CountNotificationsUnread(context.Context, *CountNotificationsUnreadRequest) (*CountNotificationsUnreadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CountNotificationsUnread not implemented")
}
func (UnimplementedNotiServiceServer) ReadNotification(context.Context, *ReadNotificationRequest) (*ReadNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadNotification not implemented")
}
func (UnimplementedNotiServiceServer) mustEmbedUnimplementedNotiServiceServer() {}

// UnsafeNotiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotiServiceServer will
// result in compilation errors.
type UnsafeNotiServiceServer interface {
	mustEmbedUnimplementedNotiServiceServer()
}

func RegisterNotiServiceServer(s grpc.ServiceRegistrar, srv NotiServiceServer) {
	s.RegisterService(&NotiService_ServiceDesc, srv)
}

func _NotiService_GetNotifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNotificationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotiServiceServer).GetNotifications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotiService_GetNotifications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotiServiceServer).GetNotifications(ctx, req.(*GetNotificationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotiService_CountNotificationsUnread_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountNotificationsUnreadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotiServiceServer).CountNotificationsUnread(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotiService_CountNotificationsUnread_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotiServiceServer).CountNotificationsUnread(ctx, req.(*CountNotificationsUnreadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotiService_ReadNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotiServiceServer).ReadNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotiService_ReadNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotiServiceServer).ReadNotification(ctx, req.(*ReadNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotiService_ServiceDesc is the grpc.ServiceDesc for NotiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "noti.v1.NotiService",
	HandlerType: (*NotiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNotifications",
			Handler:    _NotiService_GetNotifications_Handler,
		},
		{
			MethodName: "CountNotificationsUnread",
			Handler:    _NotiService_CountNotificationsUnread_Handler,
		},
		{
			MethodName: "ReadNotification",
			Handler:    _NotiService_ReadNotification_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "noti/v1/noti.proto",
}
