// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package postgresql

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type UploadAttachment struct {
	ID             uuid.UUID      `json:"id"`
	AttachableType sql.NullString `json:"attachable_type"`
	AttachableID   uuid.NullUUID  `json:"attachable_id"`
	UserID         uuid.UUID      `json:"user_id"`
	Filename       string         `json:"filename"`
	Extension      string         `json:"extension"`
	MimeType       sql.NullString `json:"mime_type"`
	Folder         sql.NullString `json:"folder"`
	VersionID      sql.NullString `json:"version_id"`
	Url            string         `json:"url"`
	UrlThumbnail   sql.NullString `json:"url_thumbnail"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}
