// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: query.sql

package postgresql

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const create = `-- name: Create :one
INSERT INTO upload.attachments 
    (
        id,
        user_id, 
        entity_upload_id, 
        filename, 
        extension,
        mime_type,
        folder,
        url,
        url_thumbnail)
VALUES ($1, $2, $3, $4, $5, $6, $7 ,$8 , $9) RETURNING id, attachable_type, attachable_id, user_id, entity_upload_id, filename, extension, mime_type, folder, url, url_thumbnail, created_at, updated_at
`

type CreateParams struct {
	ID             uuid.UUID      `json:"id"`
	UserID         uuid.UUID      `json:"user_id"`
	EntityUploadID sql.NullString `json:"entity_upload_id"`
	Filename       string         `json:"filename"`
	Extension      string         `json:"extension"`
	MimeType       sql.NullString `json:"mime_type"`
	Folder         sql.NullString `json:"folder"`
	Url            string         `json:"url"`
	UrlThumbnail   sql.NullString `json:"url_thumbnail"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (UploadAttachment, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.UserID,
		arg.EntityUploadID,
		arg.Filename,
		arg.Extension,
		arg.MimeType,
		arg.Folder,
		arg.Url,
		arg.UrlThumbnail,
	)
	var i UploadAttachment
	err := row.Scan(
		&i.ID,
		&i.AttachableType,
		&i.AttachableID,
		&i.UserID,
		&i.EntityUploadID,
		&i.Filename,
		&i.Extension,
		&i.MimeType,
		&i.Folder,
		&i.Url,
		&i.UrlThumbnail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM upload.attachments WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const deleteByIds = `-- name: DeleteByIds :exec
DELETE FROM upload.attachments WHERE id = ANY($1::uuid[])
`

func (q *Queries) DeleteByIds(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteByIds, pq.Array(dollar_1))
	return err
}

const get = `-- name: Get :one
SELECT id, attachable_type, attachable_id, user_id, entity_upload_id, filename, extension, mime_type, folder, url, url_thumbnail, created_at, updated_at FROM upload.attachments WHERE id = $1
`

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (UploadAttachment, error) {
	row := q.db.QueryRowContext(ctx, get, id)
	var i UploadAttachment
	err := row.Scan(
		&i.ID,
		&i.AttachableType,
		&i.AttachableID,
		&i.UserID,
		&i.EntityUploadID,
		&i.Filename,
		&i.Extension,
		&i.MimeType,
		&i.Folder,
		&i.Url,
		&i.UrlThumbnail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAttachmentsByOptional = `-- name: GetAttachmentsByOptional :many
SELECT id, attachable_type, attachable_id, user_id, entity_upload_id, filename, extension, mime_type, folder, url, url_thumbnail, created_at, updated_at FROM upload.attachments 
WHERE attachable_type = $1 
AND mime_type LIKE '%' || $2 ||'%'
AND (entity_upload_id = $3 OR $3 IS NULL)
ORDER BY created_at DESC LIMIT $4 OFFSET $5
`

type GetAttachmentsByOptionalParams struct {
	AttachableType sql.NullString `json:"attachable_type"`
	Column2        sql.NullString `json:"column_2"`
	EntityUploadID sql.NullString `json:"entity_upload_id"`
	Limit          int32          `json:"limit"`
	Offset         int32          `json:"offset"`
}

func (q *Queries) GetAttachmentsByOptional(ctx context.Context, arg GetAttachmentsByOptionalParams) ([]UploadAttachment, error) {
	rows, err := q.db.QueryContext(ctx, getAttachmentsByOptional,
		arg.AttachableType,
		arg.Column2,
		arg.EntityUploadID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadAttachment
	for rows.Next() {
		var i UploadAttachment
		if err := rows.Scan(
			&i.ID,
			&i.AttachableType,
			&i.AttachableID,
			&i.UserID,
			&i.EntityUploadID,
			&i.Filename,
			&i.Extension,
			&i.MimeType,
			&i.Folder,
			&i.Url,
			&i.UrlThumbnail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttachmentsByType = `-- name: GetAttachmentsByType :many
SELECT id, attachable_type, attachable_id, user_id, entity_upload_id, filename, extension, mime_type, folder, url, url_thumbnail, created_at, updated_at FROM upload.attachments WHERE attachable_type = $1 AND attachable_id = $2 ORDER BY updated_at
`

type GetAttachmentsByTypeParams struct {
	AttachableType sql.NullString `json:"attachable_type"`
	AttachableID   uuid.NullUUID  `json:"attachable_id"`
}

func (q *Queries) GetAttachmentsByType(ctx context.Context, arg GetAttachmentsByTypeParams) ([]UploadAttachment, error) {
	rows, err := q.db.QueryContext(ctx, getAttachmentsByType, arg.AttachableType, arg.AttachableID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadAttachment
	for rows.Next() {
		var i UploadAttachment
		if err := rows.Scan(
			&i.ID,
			&i.AttachableType,
			&i.AttachableID,
			&i.UserID,
			&i.EntityUploadID,
			&i.Filename,
			&i.Extension,
			&i.MimeType,
			&i.Folder,
			&i.Url,
			&i.UrlThumbnail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttachmentsByUserId = `-- name: GetAttachmentsByUserId :many
SELECT id, attachable_type, attachable_id, user_id, entity_upload_id, filename, extension, mime_type, folder, url, url_thumbnail, created_at, updated_at FROM upload.attachments 
WHERE attachable_type = $1 
AND mime_type LIKE '%' || $2 ||'%'
AND user_id = $3
AND (entity_upload_id = $6 OR entity_upload_id IS NULL)
ORDER BY created_at DESC LIMIT $4 OFFSET $5
`

type GetAttachmentsByUserIdParams struct {
	AttachableType sql.NullString `json:"attachable_type"`
	Column2        sql.NullString `json:"column_2"`
	UserID         uuid.UUID      `json:"user_id"`
	Limit          int32          `json:"limit"`
	Offset         int32          `json:"offset"`
	EntityUploadID sql.NullString `json:"entity_upload_id"`
}

func (q *Queries) GetAttachmentsByUserId(ctx context.Context, arg GetAttachmentsByUserIdParams) ([]UploadAttachment, error) {
	rows, err := q.db.QueryContext(ctx, getAttachmentsByUserId,
		arg.AttachableType,
		arg.Column2,
		arg.UserID,
		arg.Limit,
		arg.Offset,
		arg.EntityUploadID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadAttachment
	for rows.Next() {
		var i UploadAttachment
		if err := rows.Scan(
			&i.ID,
			&i.AttachableType,
			&i.AttachableID,
			&i.UserID,
			&i.EntityUploadID,
			&i.Filename,
			&i.Extension,
			&i.MimeType,
			&i.Folder,
			&i.Url,
			&i.UrlThumbnail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByIds = `-- name: GetByIds :many
SELECT id, attachable_type, attachable_id, user_id, entity_upload_id, filename, extension, mime_type, folder, url, url_thumbnail, created_at, updated_at FROM upload.attachments WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetByIds(ctx context.Context, dollar_1 []uuid.UUID) ([]UploadAttachment, error) {
	rows, err := q.db.QueryContext(ctx, getByIds, pq.Array(dollar_1))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadAttachment
	for rows.Next() {
		var i UploadAttachment
		if err := rows.Scan(
			&i.ID,
			&i.AttachableType,
			&i.AttachableID,
			&i.UserID,
			&i.EntityUploadID,
			&i.Filename,
			&i.Extension,
			&i.MimeType,
			&i.Folder,
			&i.Url,
			&i.UrlThumbnail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastAttachmentByType = `-- name: GetLastAttachmentByType :one
SELECT id, attachable_type, attachable_id, user_id, entity_upload_id, filename, extension, mime_type, folder, url, url_thumbnail, created_at, updated_at FROM upload.attachments WHERE attachable_type = $1 AND attachable_id = $2 ORDER BY updated_at DESC LIMIT 1
`

type GetLastAttachmentByTypeParams struct {
	AttachableType sql.NullString `json:"attachable_type"`
	AttachableID   uuid.NullUUID  `json:"attachable_id"`
}

func (q *Queries) GetLastAttachmentByType(ctx context.Context, arg GetLastAttachmentByTypeParams) (UploadAttachment, error) {
	row := q.db.QueryRowContext(ctx, getLastAttachmentByType, arg.AttachableType, arg.AttachableID)
	var i UploadAttachment
	err := row.Scan(
		&i.ID,
		&i.AttachableType,
		&i.AttachableID,
		&i.UserID,
		&i.EntityUploadID,
		&i.Filename,
		&i.Extension,
		&i.MimeType,
		&i.Folder,
		&i.Url,
		&i.UrlThumbnail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const update = `-- name: Update :one
UPDATE upload.attachments 
SET
    attachable_type = $2,
    attachable_id = $3,
    entity_upload_id = $4
WHERE id = $1 RETURNING id, attachable_type, attachable_id, user_id, entity_upload_id, filename, extension, mime_type, folder, url, url_thumbnail, created_at, updated_at
`

type UpdateParams struct {
	ID             uuid.UUID      `json:"id"`
	AttachableType sql.NullString `json:"attachable_type"`
	AttachableID   uuid.NullUUID  `json:"attachable_id"`
	EntityUploadID sql.NullString `json:"entity_upload_id"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (UploadAttachment, error) {
	row := q.db.QueryRowContext(ctx, update,
		arg.ID,
		arg.AttachableType,
		arg.AttachableID,
		arg.EntityUploadID,
	)
	var i UploadAttachment
	err := row.Scan(
		&i.ID,
		&i.AttachableType,
		&i.AttachableID,
		&i.UserID,
		&i.EntityUploadID,
		&i.Filename,
		&i.Extension,
		&i.MimeType,
		&i.Folder,
		&i.Url,
		&i.UrlThumbnail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateByIds = `-- name: UpdateByIds :many
UPDATE upload.attachments 
SET
    attachable_type = $2,
    attachable_id = $3,
    entity_upload_id = $4
WHERE id = ANY($1::uuid[]) RETURNING id, attachable_type, attachable_id, user_id, entity_upload_id, filename, extension, mime_type, folder, url, url_thumbnail, created_at, updated_at
`

type UpdateByIdsParams struct {
	Column1        []uuid.UUID    `json:"column_1"`
	AttachableType sql.NullString `json:"attachable_type"`
	AttachableID   uuid.NullUUID  `json:"attachable_id"`
	EntityUploadID sql.NullString `json:"entity_upload_id"`
}

func (q *Queries) UpdateByIds(ctx context.Context, arg UpdateByIdsParams) ([]UploadAttachment, error) {
	rows, err := q.db.QueryContext(ctx, updateByIds,
		pq.Array(arg.Column1),
		arg.AttachableType,
		arg.AttachableID,
		arg.EntityUploadID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UploadAttachment
	for rows.Next() {
		var i UploadAttachment
		if err := rows.Scan(
			&i.ID,
			&i.AttachableType,
			&i.AttachableID,
			&i.UserID,
			&i.EntityUploadID,
			&i.Filename,
			&i.Extension,
			&i.MimeType,
			&i.Folder,
			&i.Url,
			&i.UrlThumbnail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
