// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: query.sql

package postgresql

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const create = `-- name: Create :one
INSERT INTO upload.attachments 
    (
        id,
        user_id, 
        filename, 
        extension,
        mime_type,
        version_id,
        url,
        url_thumbnail)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, attachable_type, attachable_id, user_id, filename, extension, mime_type, folder, version_id, url, url_thumbnail, created_at, updated_at
`

type CreateParams struct {
	ID           uuid.UUID      `json:"id"`
	UserID       uuid.UUID      `json:"user_id"`
	Filename     string         `json:"filename"`
	Extension    string         `json:"extension"`
	MimeType     sql.NullString `json:"mime_type"`
	VersionID    sql.NullString `json:"version_id"`
	Url          string         `json:"url"`
	UrlThumbnail sql.NullString `json:"url_thumbnail"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (UploadAttachment, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.UserID,
		arg.Filename,
		arg.Extension,
		arg.MimeType,
		arg.VersionID,
		arg.Url,
		arg.UrlThumbnail,
	)
	var i UploadAttachment
	err := row.Scan(
		&i.ID,
		&i.AttachableType,
		&i.AttachableID,
		&i.UserID,
		&i.Filename,
		&i.Extension,
		&i.MimeType,
		&i.Folder,
		&i.VersionID,
		&i.Url,
		&i.UrlThumbnail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM upload.attachments WHERE id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const get = `-- name: Get :one
SELECT id, attachable_type, attachable_id, user_id, filename, extension, mime_type, folder, version_id, url, url_thumbnail, created_at, updated_at FROM upload.attachments WHERE id = $1
`

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (UploadAttachment, error) {
	row := q.db.QueryRowContext(ctx, get, id)
	var i UploadAttachment
	err := row.Scan(
		&i.ID,
		&i.AttachableType,
		&i.AttachableID,
		&i.UserID,
		&i.Filename,
		&i.Extension,
		&i.MimeType,
		&i.Folder,
		&i.VersionID,
		&i.Url,
		&i.UrlThumbnail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const update = `-- name: Update :one
UPDATE upload.attachments 
SET
    attachable_type = $2,
    attachable_id = $3
WHERE id = $1 RETURNING id, attachable_type, attachable_id, user_id, filename, extension, mime_type, folder, version_id, url, url_thumbnail, created_at, updated_at
`

type UpdateParams struct {
	ID             uuid.UUID      `json:"id"`
	AttachableType sql.NullString `json:"attachable_type"`
	AttachableID   uuid.NullUUID  `json:"attachable_id"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (UploadAttachment, error) {
	row := q.db.QueryRowContext(ctx, update, arg.ID, arg.AttachableType, arg.AttachableID)
	var i UploadAttachment
	err := row.Scan(
		&i.ID,
		&i.AttachableType,
		&i.AttachableID,
		&i.UserID,
		&i.Filename,
		&i.Extension,
		&i.MimeType,
		&i.Folder,
		&i.VersionID,
		&i.Url,
		&i.UrlThumbnail,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
