// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/dinhcanh303/go-microservices/cmd/upload/config"
	"github.com/dinhcanh303/go-microservices/internal/upload/app/handlers"
	"github.com/dinhcanh303/go-microservices/internal/upload/app/router"
	"github.com/dinhcanh303/go-microservices/internal/upload/infras/repo"
	"github.com/dinhcanh303/go-microservices/internal/upload/usecases/uploads"
	"github.com/dinhcanh303/go-microservices/pkg/config"
	"github.com/dinhcanh303/go-microservices/pkg/minio"
	"github.com/dinhcanh303/go-microservices/pkg/postgres"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, cfgMinio *configs.Minio, dbConnStr postgres.DBConnString, grpcServer *grpc.Server) (*App, func(), error) {
	dbEngine, cleanup, err := dbEngineFunc(dbConnStr)
	if err != nil {
		return nil, nil, err
	}
	attachmentRepo := repo.NewAttachmentRepo(dbEngine)
	minioService, cleanup2, err := minioFunc(cfgMinio)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	useCase := uploads.NewUploadService(attachmentRepo, minioService)
	useCaseGRPC := uploads.NewUploadGRPCService(attachmentRepo)
	uploadHandler := handlers.NewUploadHandler(useCase)
	uploadServiceServer := router.NewGRPCUploadServer(grpcServer, cfg, useCaseGRPC)
	app := New(cfg, cfgMinio, dbEngine, useCase, useCaseGRPC, uploadHandler, uploadServiceServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func dbEngineFunc(url postgres.DBConnString) (postgres.DBEngine, func(), error) {
	db, err := postgres.NewPostgresDB(url)
	if err != nil {
		return nil, nil, err
	}
	return db, func() { db.Close() }, nil
}

func minioFunc(cfg *configs.Minio) (minio.MinioService, func(), error) {
	return minio.NewMinio(cfg), func() {}, nil
}
