// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/dinhcanh303/go-microservices/cmd/upload/config"
	"github.com/dinhcanh303/go-microservices/internal/upload/app/handlers"
	"github.com/dinhcanh303/go-microservices/internal/upload/app/router"
	"github.com/dinhcanh303/go-microservices/internal/upload/infras/repo"
	"github.com/dinhcanh303/go-microservices/internal/upload/usecases/uploads"
	"github.com/dinhcanh303/go-microservices/pkg/config"
	"github.com/dinhcanh303/go-microservices/pkg/minio"
	"github.com/dinhcanh303/go-microservices/pkg/postgres"
	"github.com/dinhcanh303/go-microservices/pkg/redis"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, cfg2 *configs.Redis, cfgMinio *configs.Minio, dbConnStr postgres.DBConnString, dbReadConnStr postgres.DBConnReadString, grpcServer *grpc.Server) (*App, func(), error) {
	dbEngine, cleanup, err := dbEngineFunc(dbConnStr, dbReadConnStr)
	if err != nil {
		return nil, nil, err
	}
	attachmentRepo := repo.NewAttachmentRepo(dbEngine)
	redisEngine, cleanup2, err := redisEngineFunc(cfg2)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	minioService, cleanup3, err := minioFunc(cfgMinio)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	useCase := uploads.NewUploadService(attachmentRepo, redisEngine, minioService)
	useCaseGRPC := uploads.NewUploadGRPCService(attachmentRepo, redisEngine)
	uploadHandler := handlers.NewUploadHandler(useCase)
	uploadServiceServer := router.NewGRPCUploadServer(grpcServer, cfg, useCaseGRPC)
	app := New(cfg, cfgMinio, dbEngine, useCase, useCaseGRPC, uploadHandler, uploadServiceServer)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func dbEngineFunc(url postgres.DBConnString, urlRead postgres.DBConnReadString) (postgres.DBEngine, func(), error) {
	db, err := postgres.NewPostgresDB(url, urlRead)
	if err != nil {
		return nil, nil, err
	}
	return db, func() { db.Close() }, nil
}

func minioFunc(cfg *configs.Minio) (minio.MinioService, func(), error) {
	return minio.NewMinio(cfg), func() {}, nil
}

func redisEngineFunc(config2 *configs.Redis) (redis.RedisEngine, func(), error) {
	redis2, err := redis.NewRedisClient(config2)
	if err != nil {
		return nil, nil, err
	}
	return redis2, func() {
		redis2.Close()
	}, nil
}
