// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/dinhcanh303/go-microservices/cmd/like/config"
	"github.com/dinhcanh303/go-microservices/internal/like/app/router"
	"github.com/dinhcanh303/go-microservices/internal/like/infras"
	grpc2 "github.com/dinhcanh303/go-microservices/internal/like/infras/grpc"
	"github.com/dinhcanh303/go-microservices/internal/like/infras/repo"
	"github.com/dinhcanh303/go-microservices/internal/like/usecases/likes"
	"github.com/dinhcanh303/go-microservices/pkg/config"
	"github.com/dinhcanh303/go-microservices/pkg/postgres"
	"github.com/dinhcanh303/go-microservices/pkg/rabbitmq"
	"github.com/dinhcanh303/go-microservices/pkg/rabbitmq/publisher"
	"github.com/dinhcanh303/go-microservices/pkg/redis"
	"github.com/rabbitmq/amqp091-go"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, cfg2 *configs.Redis, dbConnStr postgres.DBConnString, dbReadConnStr postgres.DBConnReadString, rabbitMQConnStr rabbitmq.RabbitMQConnStr, grpcServer *grpc.Server) (*App, func(), error) {
	dbEngine, cleanup, err := dbEngineFunc(dbConnStr, dbReadConnStr)
	if err != nil {
		return nil, nil, err
	}
	likeRepo := repo.NewLikeRepo(dbEngine)
	redisEngine, cleanup2, err := redisEngineFunc(cfg2)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	connection, cleanup3, err := rabbitMQFunc(rabbitMQConnStr)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	eventPublisher, err := publisher.NewPublisher(connection)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	notiEventPublisher := infras.NewNotiEventPublisher(eventPublisher)
	postDomainService, err := grpc2.NewGRPCPostClient(cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	commentDomainService, err := grpc2.NewGRPCCommentClient(cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	useCase := likes.NewService(likeRepo, redisEngine, notiEventPublisher, postDomainService, commentDomainService)
	likeServiceServer := router.NewGRPCLikeServer(grpcServer, cfg, useCase)
	app := New(cfg, dbEngine, useCase, connection, likeServiceServer, notiEventPublisher, eventPublisher)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func dbEngineFunc(url postgres.DBConnString, urlRead postgres.DBConnReadString) (postgres.DBEngine, func(), error) {
	db, err := postgres.NewPostgresDB(url, urlRead)
	if err != nil {
		return nil, nil, err
	}
	return db, func() { db.Close() }, nil
}

func redisEngineFunc(config2 *configs.Redis) (redis.RedisEngine, func(), error) {
	redis2, err := redis.NewRedisClient(config2)
	if err != nil {
		return nil, nil, err
	}
	return redis2, func() {
		redis2.Close()
	}, nil
}

func rabbitMQFunc(url rabbitmq.RabbitMQConnStr) (*amqp091.Connection, func(), error) {
	conn, err := rabbitmq.NewRabbitMQConn(url)
	if err != nil {
		return nil, nil, err
	}
	return conn, func() { conn.Close() }, nil
}
