// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/dinhcanh303/go-microservices/cmd/auth/config"
	"github.com/dinhcanh303/go-microservices/internal/auth/app/router"
	"github.com/dinhcanh303/go-microservices/internal/auth/infras"
	grpc2 "github.com/dinhcanh303/go-microservices/internal/auth/infras/grpc"
	"github.com/dinhcanh303/go-microservices/internal/auth/infras/repo"
	"github.com/dinhcanh303/go-microservices/internal/auth/usecases/auth"
	"github.com/dinhcanh303/go-microservices/internal/auth/usecases/keys"
	"github.com/dinhcanh303/go-microservices/pkg/config"
	"github.com/dinhcanh303/go-microservices/pkg/ldap"
	"github.com/dinhcanh303/go-microservices/pkg/postgres"
	"github.com/dinhcanh303/go-microservices/pkg/rabbitmq"
	"github.com/dinhcanh303/go-microservices/pkg/rabbitmq/publisher"
	"github.com/dinhcanh303/go-microservices/pkg/token"
	"github.com/rabbitmq/amqp091-go"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, cfgLdap *configs.Ldap, dbConnStr postgres.DBConnString, dbReadConnStr postgres.DBConnReadString, rabbitMQConnStr rabbitmq.RabbitMQConnStr, grpcServer *grpc.Server) (*App, func(), error) {
	dbEngine, cleanup, err := dbEngineFunc(dbConnStr, dbReadConnStr)
	if err != nil {
		return nil, nil, err
	}
	userRepo := repo.NewUserRepo(dbEngine)
	keyRepo := repo.NewKeyRepo(dbEngine)
	useCase := keys.NewUseCase(keyRepo)
	ldapClient, cleanup2, err := ldapClientFunc(cfgLdap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	jwt := jwtFunc()
	connection, cleanup3, err := rabbitMQFunc(rabbitMQConnStr)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	eventPublisher, err := publisher.NewPublisher(connection)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userCreatedEventPublisher := infras.NewUserCreatedEventPublisher(eventPublisher)
	userDeletedEventPublisher := infras.NewUserDeletedEventPublisher(eventPublisher)
	authUseCase := auth.NewUseCase(userRepo, useCase, ldapClient, jwt, userCreatedEventPublisher, userDeletedEventPublisher)
	uploadDomainService, err := grpc2.NewGRPCUploadClient(cfg)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	authServiceServer := router.NewAuthGRPCServer(grpcServer, cfg, authUseCase, useCase, uploadDomainService)
	app := New(cfg, cfgLdap, dbEngine, authUseCase, authServiceServer, userCreatedEventPublisher, userDeletedEventPublisher, uploadDomainService)
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func dbEngineFunc(url postgres.DBConnString, urlRead postgres.DBConnReadString) (postgres.DBEngine, func(), error) {
	db, err := postgres.NewPostgresDB(url, urlRead)
	if err != nil {
		return nil, nil, err
	}
	return db, func() { db.Close() }, nil
}

func ldapClientFunc(config2 *configs.Ldap) (ldap.LdapClient, func(), error) {
	ldapClient := ldap.NewLdapClient(config2, []string{""})
	return ldapClient, func() { ldapClient.Close() }, nil
}

func jwtFunc() token.JWT {
	jwt := token.NewJWTMaker()
	return jwt
}

func rabbitMQFunc(url rabbitmq.RabbitMQConnStr) (*amqp091.Connection, func(), error) {
	conn, err := rabbitmq.NewRabbitMQConn(url)
	if err != nil {
		return nil, nil, err
	}
	return conn, func() { conn.Close() }, nil
}
