// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/dinhcanh303/go-microservices/cmd/gateway/config"
	"github.com/dinhcanh303/go-microservices/internal/auth/app/router"
	"github.com/dinhcanh303/go-microservices/internal/auth/infras/repo"
	"github.com/dinhcanh303/go-microservices/internal/auth/usecases/auth"
	"github.com/dinhcanh303/go-microservices/internal/auth/usecases/keys"
	"github.com/dinhcanh303/go-microservices/pkg/config"
	"github.com/dinhcanh303/go-microservices/pkg/ldap"
	"github.com/dinhcanh303/go-microservices/pkg/postgres"
	"github.com/dinhcanh303/go-microservices/pkg/token"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, cfgLdap *configs.Ldap, dbConnStr postgres.DBConnString, grpcServer *grpc.Server) (*App, func(), error) {
	dbEngine, cleanup, err := dbEngineFunc(dbConnStr)
	if err != nil {
		return nil, nil, err
	}
	userRepo := repo.NewUserRepo(dbEngine)
	keyRepo := repo.NewKeyRepo(dbEngine)
	useCase := keys.NewUseCase(keyRepo)
	ldapClient, cleanup2, err := ldapClientFunc(cfgLdap)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	jwt := jwtFunc()
	authUseCase := auth.NewUseCase(userRepo, useCase, ldapClient, jwt)
	authServiceServer := router.NewAuthGRPCServer(grpcServer, cfg, authUseCase, useCase)
	app := New(cfg, cfgLdap, dbEngine, authUseCase, authServiceServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

func dbEngineFunc(url postgres.DBConnString) (postgres.DBEngine, func(), error) {
	db, err := postgres.NewPostgresDB(url)
	if err != nil {
		return nil, nil, err
	}
	return db, func() { db.Close() }, nil
}

func ldapClientFunc(config2 *configs.Ldap) (ldap.LdapClient, func(), error) {
	ldapClient := ldap.NewLdapClient(config2, []string{""})
	return ldapClient, func() { ldapClient.Close() }, nil
}

func jwtFunc() token.JWT {
	jwt := token.NewJWTMaker()
	return jwt
}
