syntax="proto3";
package auth;
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "google/protobuf/timestamp.proto";
import "validate/validate.proto";

option go_package = "github.com/dinhcanh303/go-microservice/proto/gen";

service AuthService {
    rpc SignIn(SignInRequest) returns (SignInResponse){
        option (google.api.http) = {
            post: "/api/v1/auth/signin",
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "SignIn application"
            description: ""
        };
    }
    rpc SignUp(SignUpRequest) returns (SignUpResponse){
        option (google.api.http) = {
            post: "/api/v1/auth/signup",
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "SignUp application"
            description: ""
        };
    }
    rpc Verify(VerifyRequest) returns (VerifyResponse){
        option (google.api.http) = {
            get: "/api/v1/auth/verify",
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Verify token"
            description: ""
        };
    }
    rpc Logout(LogoutRequest) returns (LogoutResponse){
        option (google.api.http) = {
            get: "/api/v1/logout",
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Logout"
            description: ""
        };
    }
    rpc HandleRefreshToken(HandleRefreshTokenRequest) returns (HandleRefreshTokenResponse){
        option (google.api.http) = {
            get: "/api/v1/refresh-token",
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Handle Refresh Token"
            description: ""
        };
    }
    rpc GetAllUserIdOfCompanyByUserId(GetAllUserIdOfCompanyByUserIdRequest) returns (GetAllUserIdOfCompanyByUserIdResponse){
        option (google.api.http) = {
            get: "/api/v1/users/{user_id}/user-ids",
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get All User Id By User Id"
            description: ""
        };
    }
    rpc Profile(GetProfileRequest) returns (GetProfileResponse){
        option (google.api.http) = {
            get: "/api/v1/profile",
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get Profile of User"
            description: ""
        };
    }
}
message GetProfileRequest{
    string id = 1;
}
message GetProfileResponse{
    User user=1;
}
message GetAllUserIdOfCompanyByUserIdRequest{
    string user_id = 1;
}
message GetAllUserIdOfCompanyByUserIdResponse{
    repeated string user_ids = 1;
}
message LogoutRequest{}

message LogoutResponse{}

message HandleRefreshTokenRequest {
}
message HandleRefreshTokenResponse {
    User user =1;
    string access_token = 2;
    string refresh_token = 3;
}
message Payload {
    string id = 1;
    string email = 2;
    string fullname = 3;
    string role = 4;
    string avatar_url = 5;
}
message SignInRequest{
    string email = 1;
    string password = 2;
}

message SignInResponse{
    User user =1;
    string access_token = 2;
    string refresh_token = 3;
}
message SignUpRequest{
    string email = 1;
    string password = 2;
    string first_name = 3;
    string last_name = 4;
}

message SignUpResponse{
    User user =1;
    string access_token = 2;
    string refresh_token = 3;
}
message User {
    string id = 1;
    string email = 2;
    string first_name = 3;
    string last_name = 4;
    string full_name = 5;
    string avatar_url = 6;
    string thumbnail_url = 7;
    google.protobuf.Timestamp created_at = 8;
    google.protobuf.Timestamp updated_at = 9;
}
message VerifyRequest{}
message VerifyResponse{}