syntax="proto3";
package auth;
import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "google/protobuf/timestamp.proto";
import "validate/validate.proto";

option go_package = "github.com/dinhcanh303/go-microservice/proto/gen";

service AuthService {
    rpc SignIn(SignInRequest) returns (SignInResponse){
        option (google.api.http) = {
            post: "/api/v1/auth/signin",
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "SignIn application"
            description: ""
        };
    }
    rpc SignUp(SignUpRequest) returns (SignUpResponse){
        option (google.api.http) = {
            post: "/api/v1/auth/signup",
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "SignUp application"
            description: ""
        };
    }
    rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse){
        option (google.api.http) = {
            post: "/api/v1/refresh-token",
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Refresh Token"
            description: ""
        };
    }
    rpc FindKeyByUserID(FindKeyByUserIDRequest) returns (FindKeyByUserIDResponse){
        option (google.api.http) = {
            post: "/api/v1/keys/{user_id}",
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Find Key"
            description: ""
        };
    }
}
message RefreshTokenRequest {
    string refresh_token = 1;
    string user_id = 2;
}
message RefreshTokenResponse {
    User user =1;
    string access_token = 2;
    string refresh_token = 3;
}
message FindKeyByUserIDRequest {
    string user_id = 1;
}
message FindKeyByUserIDResponse {
    int32 id=1;
    string user_id=2;
    string public_key=3;
    string private_key=4;
    string refresh_token = 5;
    repeated string refresh_token_used = 6;
    google.protobuf.Timestamp created_at = 7;
    google.protobuf.Timestamp updated_at = 8;
}
message Payload {
    string id = 1;
    string email = 2;
    string fullname = 3;
    string role = 4;
    string avatar_url = 5;
}
message SignInRequest{
    string email = 1;
    string password = 2;
}

message SignInResponse{
    User user =1;
    string access_token = 2;
    string refresh_token = 3;
}
message SignUpRequest{
    string email = 1;
    string password = 2;
    string first_name = 3;
    string last_name = 4;
}

message SignUpResponse{
    User user =1;
    string access_token = 2;
    string refresh_token = 3;
}
message User {
    string id = 1;
    string email = 2;
    string first_name = 3;
    string last_name = 4;
    string full_name = 5;
    google.protobuf.Timestamp created_at = 6;
    google.protobuf.Timestamp updated_at = 7;
}