syntax="proto3";

package commentapi;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "google/protobuf/timestamp.proto";
import "like.proto";
import "upload.proto";
import "auth.proto";

option go_package = "github.com/dinhcanh303/go-microsevices/proto/gen";

service CommentService {
    rpc CreateComment(CreateCommentRequest) returns (CreateCommentResponse){
        option (google.api.http) = {
            post: "/api/v1/comments"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Create Comment"
            description: ""
        };
    }
    rpc GetComment(GetCommentRequest) returns (GetCommentResponse){
        option (google.api.http) = {
            get: "/api/v1/comments/{id}"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get Comment"
            description: ""
        };
    }
    rpc UpdateComment(UpdateCommentRequest) returns (UpdateCommentResponse){
        option (google.api.http) = {
            put: "/api/v1/comments/{comment.id}"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Update Comment"
            description: ""
        };
    }
    rpc DeleteComment(DeleteCommentRequest) returns (DeleteCommentResponse){
        option (google.api.http) = {
            delete: "/api/v1/comments/{id}"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Delete Comment"
            description: ""
        };
    }
    rpc GetCommentsByPostID(GetCommentsByPostIDRequest) returns (GetCommentsByPostIDResponse){
        option (google.api.http) = {
            get: "/api/v1/posts/{post_id}/comments"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get Comment By Post ID"
            description: ""
        };
    }
    rpc GetCommentsByCommentID(GetCommentsByCommentIDRequest) returns (GetCommentsByCommentIDResponse){
        option (google.api.http) = {
            get: "/api/v1/comments/{comment_id}/comments"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get Comment By Comment ID"
            description: ""
        };
    }
    rpc CountCommentByPostID(CountCommentByPostIDRequest) returns (CountCommentByPostIDResponse){
        option (google.api.http) = {
            get: "/api/v1/posts/{post_id}/comments/count"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Count Comment By Post ID"
            description: ""
        };
    }
    rpc CountCommentByCommentID(CountCommentByCommentIDRequest) returns (CountCommentByCommentIDResponse){
        option (google.api.http) = {
            get: "/api/v1/comments/{comment_id}/count"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Count Comment By Comment ID"
            description: ""
        };
    }
}


message CreateCommentRequest {
    CommentRequest comment =1;
}
message CreateCommentResponse {
    Comment comment = 1;
}
message GetCommentRequest {
    string id = 1;
}
message GetCommentResponse {
    Comment comment = 1;
}
message UpdateCommentRequest {
    Comment comment = 1;
}
message UpdateCommentResponse {
    Comment comment = 1;
}
message DeleteCommentRequest {
    string id = 1;
}
message DeleteCommentResponse {
    bool deleted = 1;
}
message GetCommentsByPostIDRequest {
    string post_id =1;
    int32 limit = 2;
    int32 offset = 3;
}
message GetCommentsByCommentIDRequest {
    string comment_id =1;
    int32 limit = 2;
    int32 offset = 3;
}
message CountCommentByPostIDRequest {
    string post_id = 1;
}
message CountCommentByPostIDResponse {
    int64 count = 1;
}
message CountCommentByCommentIDRequest {
    string comment_id = 1;
}
message CountCommentByCommentIDResponse {
    int64 count = 1;
}
message GetCommentsByPostIDResponse {
    repeated CommentHasChildren comments = 1;
}
message GetCommentsByCommentIDResponse {
    repeated CommentHasMetadata comments = 1;
}
message CommentRequest {
    string post_id = 1;
    string reply_id = 2;
    repeated string tag_ids = 3;
    string content = 4;
    string parent_comment_id = 5;
}
message Comment {
    string id = 1;
    string post_id = 2;
    string user_id = 3;
    string reply_id = 4;
    repeated string tag_ids = 5;
    string content = 6;
    string parent_comment_id = 7;
    google.protobuf.Timestamp created_at = 8;
    google.protobuf.Timestamp updated_at = 9;
}
message CommentHasMetadata {
    string id = 1;
    string post_id = 2;
    string user_id = 3;
    string reply_id = 4;
    repeated string tag_ids = 5;
    string content = 6;
    string parent_comment_id = 7;
    authapi.User user = 8;
    likeapi.LikeInfo likes = 9;
    repeated uploadapi.Attachment attachments = 10;
    google.protobuf.Timestamp created_at = 11;
    google.protobuf.Timestamp updated_at = 12;
}
message CommentHasChildren {
    string id = 1;
    string post_id = 2;
    string user_id = 3;
    string reply_id = 4;
    repeated string tag_ids = 5;
    string content = 6;
    string parent_comment_id = 7;
    authapi.User user = 8;
    repeated CommentHasMetadata children = 9;
    likeapi.LikeInfo likes = 10;
    repeated uploadapi.Attachment attachments = 11;
    google.protobuf.Timestamp created_at = 12;
    google.protobuf.Timestamp updated_at = 13;
}