syntax="proto3";

package group;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/dinhcanh303/go-microsevices/proto/gen";

service GroupService {
    rpc CreateGroup(CreateGroupRequest) returns (CreateGroupResponse){
        option (google.api.http) = {
            post: "/v1/api/groups"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Create group"
            description: ""
        };
    }
    rpc GetGroup(GetGroupRequest) returns (GetGroupResponse){
        option (google.api.http) = {
            get: "/v1/api/groups/{id}"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get group"
            description: ""
        };
    }
    rpc UpdateGroup(UpdateGroupRequest) returns (UpdateGroupResponse){
        option (google.api.http) = {
            put: "/v1/api/groups/{group.id}"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Update group"
            description: ""
        };
    }
    rpc DeleteGroup(DeleteGroupRequest) returns (DeleteGroupResponse){
        option (google.api.http) = {
            delete: "/v1/api/groups/{id}"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Delete group"
            description: ""
        };
    }
    rpc GetAllGroupByUserId(GetAllGroupByUserIdRequest) returns (GetAllGroupByUserIdResponse){
        option (google.api.http) = {
            get: "/v1/api/groups/{user_id}"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get all group member"
            description: ""
        };
    }
    rpc GetAllGroupIdByUserId(GetAllGroupIdByUserIdRequest) returns (GetAllGroupIdByUserIdResponse){
        option (google.api.http) = {
            get: "/v1/api/group-ids/{user_id}"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get all group id by user id",
            description: ""
        };
    }
    // GroupMember
    rpc CreateGroupMember(CreateGroupMemberRequest) returns (CreateGroupMemberResponse){
        option (google.api.http) = {
            post: "/v1/api/group-members"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Create group member"
            description: ""
        };
    }
    rpc UpdateGroupMember(UpdateGroupMemberRequest) returns (UpdateGroupMemberResponse){
        option (google.api.http) = {
            put: "/v1/api/group-members/{group_member.id}"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Update group member"
            description: ""
        };
    }
    rpc DeleteGroupMember(DeleteGroupMemberRequest) returns (DeleteGroupMemberResponse){
        option (google.api.http) = {
            delete: "/v1/api/group-members/{id}"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Delete group member"
            description: ""
        };
    }
    rpc GetAllGroupMembers(GetAllGroupMembersRequest) returns (GetAllGroupMembersResponse){
        option (google.api.http) = {
            get: "/v1/api/group-members/{groupId}"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get all group member"
            description: ""
        };
    }
    

}

message CreateGroupRequest {
    GroupRequest group = 1;
}
message CreateGroupResponse {
    GroupResponse group = 1;
}
message CreateGroupMemberRequest {
    GroupMemberRequest group_member = 1;
}
message CreateGroupMemberResponse {
    GroupMemberResponse group_member = 1;
}
message GetGroupRequest {
    string id = 1;
}
message GetAllGroupMembersRequest {
    string groupId = 1;
}
message GetAllGroupMembersResponse {
    repeated GroupMemberResponse group_members = 1;
}
message DeleteGroupRequest {
    string id = 1;
}
message DeleteGroupResponse {
    bool deleted = 1;
}
message DeleteGroupMemberRequest {
    string id = 1;
}
message DeleteGroupMemberResponse {
    bool deleted = 1;
}
message GetGroupResponse {
    GroupResponse group = 1;
}
message UpdateGroupRequest {
    GroupResponse group = 1;
}
message UpdateGroupResponse {
    GroupResponse group = 1;
}
message UpdateGroupMemberRequest {
    GroupMemberResponse group_member = 1;
}
message UpdateGroupMemberResponse {
    GroupMemberResponse group_member = 1;
}
message GetAllGroupByUserIdRequest {
    string user_id = 1;
}
message GetAllGroupByUserIdResponse {
    repeated GroupResponse groups = 1;
}
message GetAllGroupIdByUserIdRequest {
    string user_id = 1;
}
message GetAllGroupIdByUserIdResponse {
    repeated string group_ids = 1;
}
message GroupRequest {
    string name = 1;
    string description = 2;
    int32 status = 3;
    string user_id = 4;
}
message GroupResponse {
    string id = 1;
    string name = 2;
    string description = 3;
    int32 status = 4;
    string user_id = 5;
    google.protobuf.Timestamp created_at = 6;
    google.protobuf.Timestamp updated_at = 7;
}
message GroupMemberRequest {
    string group_id = 1;
    string user_id = 2;
    int32 role = 3;
}
message GroupMemberResponse {
    string id = 1;
    string group_id = 2;
    string user_id = 3;
    int32 role = 4;
    google.protobuf.Timestamp created_at = 5;
    google.protobuf.Timestamp updated_at = 6;
}