syntax="proto3";

package go.microsevices.proto.groupapi;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/dinhcanh303/go-microsevices/proto/gen";

service GroupService {
    rpc CreateGroup(CreateGroupRequest) returns (CreateGroupResponse){
        option (google.api.http) = {
            post: "/v1/api/groups"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Create group"
            description: ""
            tags: "Group"
        };
    }
    rpc GetGroup(GetGroupRequest) returns (GetGroupResponse){
        option (google.api.http) = {
            get: "/v1/api/groups/{id}"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get group"
            description: ""
            tags: "Group"
        };
    }
    rpc UpdateGroup(UpdateGroupRequest) returns (UpdateGroupResponse){
        option (google.api.http) = {
            put: "/v1/api/groups/{group.id}"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Update group"
            description: ""
            tags: "Group"
        };
    }
    rpc DeleteGroup(DeleteGroupRequest) returns (DeleteGroupResponse){
        option (google.api.http) = {
            delete: "/v1/api/groups/{id}"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Delete group"
            description: ""
            tags: "Group"
        };
    }

}

message CreateGroupRequest {
    GroupRequest group = 1;
}
message CreateGroupResponse {
    GroupResponse group = 1;
}
message GetGroupRequest {
    string id = 1;
}
message DeleteGroupRequest {
    string id = 1;
}
message DeleteGroupResponse {
    bool deleted = 1;
}
message GetGroupResponse {
    GroupResponse group = 1;
}
message UpdateGroupRequest {
    GroupResponse group = 1;
}
message UpdateGroupResponse {
    GroupResponse group = 1;
}
message GroupRequest {
    string name = 1;
    string description = 2;
    int32 status = 3;
    string user_id = 4;
}
message GroupResponse {
    string id = 1;
    string name = 2;
    string description = 3;
    int32 status = 4;
    string user_id = 5;
    google.protobuf.Timestamp created_at = 6;
    google.protobuf.Timestamp updated_at = 7;
}