syntax="proto3";

package like;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/dinhcanh303/go-microsevices/proto/gen";

service LikeService {
    rpc CreateLike(CreateLikeRequest) returns (CreateLikeResponse){
        option (google.api.http) = {
            post: "/v1/likes"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Create Like"
            description: ""
        };
    }
    rpc UpdateLike(UpdateLikeRequest) returns (UpdateLikeResponse){
        option (google.api.http) = {
            put: "/v1/likes/{like.id}"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Update Like"
            description: ""
        };
    }
    rpc DeleteLike(DeleteLikeRequest) returns (DeleteLikeResponse){
        option (google.api.http) = {
            delete: "/v1/likes/{id}"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Delete Like"
            description: ""
        };
    }
    rpc GetLikesByPostID(GetLikesByPostIDRequest) returns (GetLikesByPostIDResponse){
        option (google.api.http) = {
            get: "/v1/posts/{post_id}/likes"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get Like by Post ID"
            description: ""
        };
    }
    rpc GetLikesByCommentID(GetLikesByCommentIDRequest) returns (GetLikesByCommentIDResponse){
        option (google.api.http) = {
            get: "/v1/comments/{comment_id}/likes"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get Like by Comment ID"
            description: ""
        };
    }
}


message CreateLikeRequest {
    LikeRequest like =1;
}
message CreateLikeResponse {
    Like like = 1;
}
message UpdateLikeRequest {
    LikeUpdateRequest like = 1;
}
message UpdateLikeResponse {
    Like like = 1;
}
message DeleteLikeRequest {
    string id = 1;
}
message DeleteLikeResponse {
    bool deleted = 1;
}

message LikeRequest {
    string emoji =1;
    string likeable_type =2;
    string likeable_id =3;
    string user_id = 4;
}
message LikeUpdateRequest {
    string id = 1;
    string emoji = 2;
}

message GetLikesByPostIDRequest {
    string post_id = 1;
}
message GetLikesByCommentIDRequest {
    string comment_id = 1;
}
message GetLikesByPostIDResponse {
    repeated Like likes = 1;
}
message GetLikesByCommentIDResponse {
    repeated Like likes = 1;
}
message Like {
    string id =1;
    string emoji =2;
    string likeable_type =3;
    string likeable_id =4;
    string user_id = 5;
    google.protobuf.Timestamp created_at = 6;
    google.protobuf.Timestamp updated_at = 7;
}
