syntax="proto3";

package notiapi;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";
import "auth.proto";

option go_package = "github.com/dinhcanh303/go-microsevices/proto/gen";

service NotiService {
    rpc GetNotifications(GetNotificationsRequest) returns (GetNotificationsResponse) {
        option (google.api.http) = {
            get: "/api/v1/notifications"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get a list of notifications by options"
            description: ""
        };
    }
    rpc CountNotificationsUnread(CountNotificationsUnreadRequest) returns (CountNotificationsUnreadResponse) {
        option (google.api.http) = {
            get: "/api/v1/notifications/count"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get count of notifications unread"
            description: ""
        };
    }
    rpc ReadNotification(ReadNotificationRequest) returns (ReadNotificationResponse) {
        option (google.api.http) = {
            put: "/api/v1/notifications/{id}"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Read a notification"
            description: ""
        };
    }

}
message CountNotificationsUnreadRequest{}
message CountNotificationsUnreadResponse{
    int64 count = 1;
}
message GetNotificationsRequest{
    int32 limit = 1;
    int32 offset = 2;
    bool options = 3;
}
message GetNotificationsResponse {
    repeated Notification notifications = 1;
}
message ReadNotificationRequest{
    int64 id = 1;
}
message ReadNotificationResponse {}
message Notification{
    int64 id = 1;
    string actor_id = 2;
    string sender_id = 3;
    authapi.User actor = 4;
    google.protobuf.Struct data = 5;
    string object_type = 6;
    string object_id = 7;
    google.protobuf.Timestamp read_at = 8;
    google.protobuf.Timestamp created_at = 9;
    google.protobuf.Timestamp updated_at = 10;
}
