syntax="proto3";

package post;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "google/protobuf/timestamp.proto";
import "upload.proto";
import "like.proto";
import "comment.proto";

option go_package = "github.com/dinhcanh303/go-microsevices/proto/gen";

service PostService {
    rpc CreatePost(CreatePostRequest) returns (CreatePostResponse){
        option (google.api.http) = {
            post: "/api/v1/posts"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Create Post"
            description: ""
        };
    }
    rpc GetPost(GetPostRequest) returns (GetPostResponse){
        option (google.api.http) = {
            get: "/api/v1/posts/{id}"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get Post"
            description: ""
        };
    }
    rpc NewFeed(NewFeedRequest) returns (NewFeedResponse){
        option (google.api.http) = {
            get: "/api/v1/feed"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get Feed"
            description: ""
        };
    }
    rpc GetPostsByGroupId(GetPostsByGroupIdRequest) returns (GetPostsByGroupIdResponse){
        option (google.api.http) = {
            get: "/api/v1/groups/{group_id}/posts"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get Posts By Group ID"
            description: ""
        };
    }
    rpc GetPostsByUserId(GetPostsByUserIdRequest) returns (GetPostsByUserIdResponse){
        option (google.api.http) = {
            get: "/api/v1/users/{user_id}/posts"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get Posts By User ID"
            description: ""
        };
    }
    rpc UpdatePost(UpdatePostRequest) returns (UpdatePostResponse){
        option (google.api.http) = {
            put: "/api/v1/posts/{post.id}"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Update Post"
            description: ""
        };
    }
    rpc DeletePost(DeletePostRequest) returns (DeletePostResponse){
        option (google.api.http) = {
            delete: "/api/v1/posts/{id}"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Delete Post"
            description: ""
        };
    }
}
message CreatePostRequest {
    PostRequest post = 1;
}
message CreatePostResponse {
    PostResponse post = 1;
}
message GetPostRequest {
    string id = 1;
}
message NewFeedRequest {
    int32 limit = 3;
    int32 offset = 4;
}
message NewFeedResponse {
    repeated GetPostResponse posts = 1;
}
message GetPostsByGroupIdRequest {
    string group_id = 1;
    int32 limit = 2;
    int32 offset = 3;
}
message GetPostsByGroupIdResponse {
    repeated GetPostResponse posts = 1;
}

message GetPostsByUserIdRequest {
    string user_id = 1;
    int32 limit = 2;
    int32 offset = 3;
}
message GetPostsByUserIdResponse {
    repeated GetPostResponse posts = 1;
}
message DeletePostRequest {
    string id = 1;
}
message DeletePostResponse {
    bool deleted = 1;
}
message GetPostResponse {
    PostResponse post = 1;
    repeated upload.Attachment attachments = 2;
    repeated like.Like likes = 3;
    repeated comment.CommentHasCommentAndLike comments = 4;
}
message UpdatePostRequest {
    PostResponse post = 1;
}
message UpdatePostResponse {
    PostResponse post = 1;
}
message ListPostRequest {
    string id = 1;
    uint32 offset = 2;
    uint32 limit = 3;
}
message ListPostResponse {
    repeated PostResponse post = 1;
}
message PostRequest {
    string title = 1;
    string content = 2;
    int32 status = 3;
    string user_id = 4;
    string group_id = 5;
}
message PostResponse {
    string id = 1;
    string title = 2;
    string content = 3;
    int32 status = 4;
    string user_id = 5;
    string group_id = 6;
    google.protobuf.Timestamp created_at = 7;
    google.protobuf.Timestamp updated_at = 8;
}