syntax="proto3";

package search;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/dinhcanh303/go-microsevices/proto/gen";

service SearchService {
    rpc Search(SearchRequest) returns (SearchResponse) {
        option (google.api.http) = {
            get: "/api/v1/search/{key_word}"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Search User and Group by Elasticsearch"
            description: ""
        };
    }
}

message SearchRequest{
    string key_word = 1;
}
message SearchResponse {
    repeated Search search = 1;
}
message Search{
    string id = 1;
    string name = 2;
    string email = 3;
    string avatar = 4;
    string type = 5;
}