syntax="proto3";

package searchapi;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/dinhcanh303/go-microsevices/proto/gen";

service SearchService {
    rpc Search(SearchRequest) returns (SearchResponse) {
        option (google.api.http) = {
            get: "/api/v1/search"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Search User and Group by Melisearch"
            description: ""
        };
    }
}

message SearchRequest{
    string q = 1;
}
message SearchResponse {
    repeated Search searches = 1;
}
message Search{
    string id = 1;
    string name = 2;
    string email = 3;
    string full_name = 4;
    string nick_name = 5;
    string position = 6;
    string avatar_url = 7;
    string profile_url = 8;
}
