syntax="proto3";

package go.microsevices.proto.uploadapi;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/dinhcanh303/go-microsevices/proto/gen";

service UploadService {
    rpc UpdateAttachment(UpdateAttachmentRequest) returns (UpdateAttachmentResponse) {
        option (google.api.http) = {
            post: "/v1/api/attachments/{attachment.id}"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Update Attachment"
            description: ""
            tags: "Upload"
        };
    }
    rpc DeleteAttachment(DeleteAttachmentRequest) returns (DeleteAttachmentResponse) {
        option (google.api.http) = {
            delete: "/v1/api/attachments/{id}"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Delete Attachment"
            description: ""
            tags: "Upload"
        };
    }

}
message UpdateAttachmentRequest{
    Attachment attachment = 1;
}
message UpdateAttachmentResponse{
    Attachment attachment = 1;
}
message DeleteAttachmentRequest{
    string id = 1;
}
message DeleteAttachmentResponse{
    bool deleted = 1;
}
message Attachment{
    string id = 1;
    string attachable_type = 2;
    string attachable_id = 3;
    string user_id = 4;
    string filename = 5;
    string extension = 6;
    string mime_type = 7;
    string folder = 8;
    string url_thumbnail = 9;
    string url = 10;
    google.protobuf.Timestamp created_at = 11;
    google.protobuf.Timestamp updated_at = 12;
}