syntax="proto3";

package upload;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/dinhcanh303/go-microsevices/proto/gen";

service UploadService {
    rpc GetAttachmentsByType(GetAttachmentsByTypeRequest) returns (GetAttachmentsByTypeResponse) {
        option (google.api.http) = {
            get: "/v1/api/attachments"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "GetAttachmentsByType"
            description: ""
        };
    }
    rpc UpdateAttachment(UpdateAttachmentRequest) returns (UpdateAttachmentResponse) {
        option (google.api.http) = {
            put: "/v1/api/attachments/{id}"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "UpdateAttachment"
            description: ""
        };
    }
}
message GetAttachmentsByTypeRequest{
    string attachable_type = 1;
    string attachable_id = 2;
}
message UpdateAttachmentRequest{
    string attachable_type = 1;
    string attachable_id = 2;
}
message GetAttachmentsByTypeResponse{
    repeated Attachment attachments = 1;
}
message UpdateAttachmentResponse{
    Attachment attachment = 1;
}
message Attachment {
    string id = 1;
    string attachable_type = 2;
    string attachable_id = 3;
    string user_id = 4;
    string filename = 5;
    string extension = 6;
    string mime_type = 7;
    string folder = 8;
    string url = 9;
    string url_thumbnail = 10;
    google.protobuf.Timestamp created_at = 11;
    google.protobuf.Timestamp updated_at = 12;
}