// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/dinhcanh303/go-microservices/cmd/search/config"
	"github.com/dinhcanh303/go-microservices/internal/search/app/router"
	"github.com/dinhcanh303/go-microservices/internal/search/eventhandlers"
	grpc2 "github.com/dinhcanh303/go-microservices/internal/search/infras/grpc"
	"github.com/dinhcanh303/go-microservices/internal/search/usecases/searches"
	"github.com/dinhcanh303/go-microservices/pkg/kafka"
	"github.com/dinhcanh303/go-microservices/pkg/meili"
	"github.com/dinhcanh303/go-microservices/pkg/rabbitmq"
	"github.com/dinhcanh303/go-microservices/pkg/rabbitmq/consumer"
	"github.com/rabbitmq/amqp091-go"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, rabbitMQConnStr rabbitmq.RabbitMQConnStr, meiliSearchConn meili.MeiliSearchConn, grpcServer *grpc.Server) (*App, func(), error) {
	connection, cleanup, err := rabbitMQFunc(rabbitMQConnStr)
	if err != nil {
		return nil, nil, err
	}
	eventConsumer, err := consumer.NewConsumer(connection)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	meiliSearch := meiliSearchFunc(meiliSearchConn)
	authDomainService, err := grpc2.NewGRPCAuthClient(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	groupDomainService, err := grpc2.NewGRPCGroupClient(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	eventHandlers := eventhandlers.NewEventHandlers(meiliSearch, authDomainService, groupDomainService)
	useCase := searches.NewService(meiliSearch)
	searchServiceServer := router.NewSearchGRPCServer(grpcServer, useCase)
	kafkaConsumer, err := kafka.NewKafkaConsumer()
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app := New(cfg, connection, eventConsumer, eventHandlers, searchServiceServer, kafkaConsumer)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

func rabbitMQFunc(url rabbitmq.RabbitMQConnStr) (*amqp091.Connection, func(), error) {
	conn, err := rabbitmq.NewRabbitMQConn(url)
	if err != nil {
		return nil, nil, err
	}
	return conn, func() { conn.Close() }, nil
}

//	func elasticSearchFunc(conn elastic.ElasticSearchConn) (elastic.ElasticSearch, error) {
//		es, err := elastic.NewElasticSearch(conn)
//		if err != nil {
//			return nil, err
//		}
//		return es, err
//	}
func meiliSearchFunc(conn meili.MeiliSearchConn) meili.MeiliSearch {
	return meili.NewMeiliSearch(conn)
}
