// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/dinhcanh303/go-microservices/cmd/search/config"
	"github.com/dinhcanh303/go-microservices/internal/search/app/router"
	"github.com/dinhcanh303/go-microservices/internal/search/eventhandlers"
	"github.com/dinhcanh303/go-microservices/pkg/elastic"
	"github.com/dinhcanh303/go-microservices/pkg/rabbitmq"
	"github.com/dinhcanh303/go-microservices/pkg/rabbitmq/comsumer"
	"github.com/rabbitmq/amqp091-go"
	"google.golang.org/grpc"
)

// Injectors from wire.go:

func InitApp(cfg *config.Config, rabbitMQConnStr rabbitmq.RabbitMQConnStr, elasticSearchConn elastic.ElasticSearchConn, grpcServer *grpc.Server) (*App, func(), error) {
	connection, cleanup, err := rabbitMQFunc(rabbitMQConnStr)
	if err != nil {
		return nil, nil, err
	}
	eventConsumer, err := consumer.NewConsumer(connection)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	elasticSearch, err := elasticSearchFunc(elasticSearchConn)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	eventHandlers := eventhandlers.NewEventHandlers(elasticSearch)
	searchServiceServer := router.NewSearchGRPCServer(grpcServer, elasticSearch)
	app := New(cfg, connection, eventConsumer, eventHandlers, searchServiceServer)
	return app, func() {
		cleanup()
	}, nil
}

// wire.go:

func rabbitMQFunc(url rabbitmq.RabbitMQConnStr) (*amqp091.Connection, func(), error) {
	conn, err := rabbitmq.NewRabbitMQConn(url)
	if err != nil {
		return nil, nil, err
	}
	return conn, func() { conn.Close() }, nil
}

func elasticSearchFunc(conn elastic.ElasticSearchConn) (elastic.ElasticSearch, error) {
	es, err := elastic.NewElasticSearch(conn)
	if err != nil {
		return nil, err
	}
	return es, err
}
