// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package postgresql

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type AuthApiKey struct {
	ID          int64                 `json:"id"`
	Key         string                `json:"key"`
	Status      bool                  `json:"status"`
	Permissions pqtype.NullRawMessage `json:"permissions"`
	CreatedAt   time.Time             `json:"created_at"`
	UpdatedAt   time.Time             `json:"updated_at"`
}

type AuthKey struct {
	ID                int64                 `json:"id"`
	UserID            uuid.UUID             `json:"user_id"`
	PublicKey         string                `json:"public_key"`
	PrivateKey        string                `json:"private_key"`
	RefreshToken      string                `json:"refresh_token"`
	RefreshTokensUsed pqtype.NullRawMessage `json:"refresh_tokens_used"`
	CreatedAt         time.Time             `json:"created_at"`
	UpdatedAt         time.Time             `json:"updated_at"`
}

type AuthUser struct {
	ID        uuid.UUID             `json:"id"`
	Email     string                `json:"email"`
	FistName  string                `json:"fist_name"`
	LastName  string                `json:"last_name"`
	FullName  sql.NullString        `json:"full_name"`
	Password  string                `json:"password"`
	UserID    uuid.UUID             `json:"user_id"`
	Roles     pqtype.NullRawMessage `json:"roles"`
	CreatedAt time.Time             `json:"created_at"`
	UpdatedAt time.Time             `json:"updated_at"`
}
