// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package postgresql

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AuthApiKey struct {
	ID          int64     `json:"id"`
	Key         string    `json:"key"`
	Status      bool      `json:"status"`
	Permissions []string  `json:"permissions"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type AuthKey struct {
	ID                int64          `json:"id"`
	UserID            uuid.UUID      `json:"user_id"`
	PublicKey         string         `json:"public_key"`
	PrivateKey        string         `json:"private_key"`
	RefreshToken      sql.NullString `json:"refresh_token"`
	RefreshTokensUsed []string       `json:"refresh_tokens_used"`
	CreatedAt         time.Time      `json:"created_at"`
	UpdatedAt         time.Time      `json:"updated_at"`
}

type AuthUser struct {
	ID          uuid.UUID       `json:"id"`
	Email       string          `json:"email"`
	FirstName   string          `json:"first_name"`
	LastName    string          `json:"last_name"`
	FullName    sql.NullString  `json:"full_name"`
	NickName    sql.NullString  `json:"nick_name"`
	AvatarUrl   sql.NullString  `json:"avatar_url"`
	ProfileUrl  sql.NullString  `json:"profile_url"`
	Role        sql.NullString  `json:"role"`
	Resigned    sql.NullBool    `json:"resigned"`
	Gender      sql.NullBool    `json:"gender"`
	Phone       sql.NullString  `json:"phone"`
	Address     sql.NullString  `json:"address"`
	Position    sql.NullString  `json:"position"`
	DateOfBirth sql.NullTime    `json:"date_of_birth"`
	Password    string          `json:"password"`
	Settings    json.RawMessage `json:"settings"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}
