// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: query.sql

package postgresql

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createKey = `-- name: CreateKey :one
INSERT INTO auth.keys
    (
        user_id,
        public_key,
        private_key
    )
VALUES ($1,$2,$3) RETURNING id, user_id, public_key, private_key, refresh_token, refresh_tokens_used, created_at, updated_at
`

type CreateKeyParams struct {
	UserID     uuid.UUID `json:"user_id"`
	PublicKey  string    `json:"public_key"`
	PrivateKey string    `json:"private_key"`
}

func (q *Queries) CreateKey(ctx context.Context, arg CreateKeyParams) (AuthKey, error) {
	row := q.db.QueryRowContext(ctx, createKey, arg.UserID, arg.PublicKey, arg.PrivateKey)
	var i AuthKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.PrivateKey,
		&i.RefreshToken,
		&i.RefreshTokensUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO auth.users
    (
        id,
        email,
        password,
        first_name,
        last_name,
        full_name
    )
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, email, first_name, last_name, full_name, password, roles, created_at, updated_at
`

type CreateUserParams struct {
	ID        uuid.UUID      `json:"id"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	FullName  sql.NullString `json:"full_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.FullName,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.Password,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteKeyByID = `-- name: DeleteKeyByID :exec
DELETE FROM auth.keys WHERE id = $1
`

func (q *Queries) DeleteKeyByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteKeyByID, id)
	return err
}

const deleteKeyByUserID = `-- name: DeleteKeyByUserID :exec
DELETE FROM auth.keys WHERE user_id = $1
`

func (q *Queries) DeleteKeyByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteKeyByUserID, userID)
	return err
}

const findKeyByRefreshToken = `-- name: FindKeyByRefreshToken :one
SELECT id, user_id, public_key, private_key, refresh_token, refresh_tokens_used, created_at, updated_at FROM auth.keys WHERE refresh_token = $1
`

func (q *Queries) FindKeyByRefreshToken(ctx context.Context, refreshToken sql.NullString) (AuthKey, error) {
	row := q.db.QueryRowContext(ctx, findKeyByRefreshToken, refreshToken)
	var i AuthKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.PrivateKey,
		&i.RefreshToken,
		&i.RefreshTokensUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findKeyByRefreshTokenUsed = `-- name: FindKeyByRefreshTokenUsed :one
SELECT id, user_id, public_key, private_key, refresh_token, refresh_tokens_used, created_at, updated_at FROM auth.keys WHERE refresh_tokens_used = $1
`

func (q *Queries) FindKeyByRefreshTokenUsed(ctx context.Context, refreshTokensUsed pqtype.NullRawMessage) (AuthKey, error) {
	row := q.db.QueryRowContext(ctx, findKeyByRefreshTokenUsed, refreshTokensUsed)
	var i AuthKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.PrivateKey,
		&i.RefreshToken,
		&i.RefreshTokensUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findKeyByUserID = `-- name: FindKeyByUserID :one
SELECT id, user_id, public_key, private_key, refresh_token, refresh_tokens_used, created_at, updated_at FROM auth.keys WHERE user_id = $1
`

func (q *Queries) FindKeyByUserID(ctx context.Context, userID uuid.UUID) (AuthKey, error) {
	row := q.db.QueryRowContext(ctx, findKeyByUserID, userID)
	var i AuthKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.PrivateKey,
		&i.RefreshToken,
		&i.RefreshTokensUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, first_name, last_name, full_name, password, roles, created_at, updated_at FROM auth.users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.Password,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, first_name, last_name, full_name, password, roles, created_at, updated_at FROM auth.users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.Password,
		&i.Roles,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateKeyByUserID = `-- name: UpdateKeyByUserID :one
UPDATE auth.keys 
SET
    public_key = COALESCE($1,public_key),
    private_key = COALESCE($2,private_key),
    refresh_token = COALESCE($3,refresh_token),
    refresh_tokens_used = COALESCE($4,refresh_tokens_used)
WHERE user_id = $5 RETURNING id, user_id, public_key, private_key, refresh_token, refresh_tokens_used, created_at, updated_at
`

type UpdateKeyByUserIDParams struct {
	PublicKey         sql.NullString        `json:"public_key"`
	PrivateKey        sql.NullString        `json:"private_key"`
	RefreshToken      sql.NullString        `json:"refresh_token"`
	RefreshTokensUsed pqtype.NullRawMessage `json:"refresh_tokens_used"`
	UserID            uuid.UUID             `json:"user_id"`
}

func (q *Queries) UpdateKeyByUserID(ctx context.Context, arg UpdateKeyByUserIDParams) (AuthKey, error) {
	row := q.db.QueryRowContext(ctx, updateKeyByUserID,
		arg.PublicKey,
		arg.PrivateKey,
		arg.RefreshToken,
		arg.RefreshTokensUsed,
		arg.UserID,
	)
	var i AuthKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.PrivateKey,
		&i.RefreshToken,
		&i.RefreshTokensUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
