// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: query.sql

package postgresql

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/lib/pq"
	"github.com/sqlc-dev/pqtype"
)

const createFollow = `-- name: CreateFollow :one
INSERT INTO auth.follows(
    follower_id,
    following_id
) VALUES ($1,$2) RETURNING follower_id, following_id, created_at, updated_at
`

type CreateFollowParams struct {
	FollowerID  uuid.UUID `json:"follower_id"`
	FollowingID uuid.UUID `json:"following_id"`
}

func (q *Queries) CreateFollow(ctx context.Context, arg CreateFollowParams) (AuthFollow, error) {
	row := q.db.QueryRowContext(ctx, createFollow, arg.FollowerID, arg.FollowingID)
	var i AuthFollow
	err := row.Scan(
		&i.FollowerID,
		&i.FollowingID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createKey = `-- name: CreateKey :one
INSERT INTO auth.keys
    (
        user_id,
        public_key,
        private_key
    )
VALUES ($1,$2,$3) RETURNING id, user_id, public_key, private_key, refresh_token, refresh_tokens_used, created_at, updated_at
`

type CreateKeyParams struct {
	UserID     uuid.UUID `json:"user_id"`
	PublicKey  string    `json:"public_key"`
	PrivateKey string    `json:"private_key"`
}

func (q *Queries) CreateKey(ctx context.Context, arg CreateKeyParams) (AuthKey, error) {
	row := q.db.QueryRowContext(ctx, createKey, arg.UserID, arg.PublicKey, arg.PrivateKey)
	var i AuthKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.PrivateKey,
		&i.RefreshToken,
		pq.Array(&i.RefreshTokensUsed),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO auth.users
    (
        id,
        email,
        password,
        first_name,
        last_name,
        full_name,
        nick_name
    )
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, email, first_name, last_name, full_name, nick_name, avatar_url, profile_url, role, resigned, gender, phone, address, position, date_of_birth, password, settings, created_at, updated_at
`

type CreateUserParams struct {
	ID        uuid.UUID      `json:"id"`
	Email     string         `json:"email"`
	Password  string         `json:"password"`
	FirstName string         `json:"first_name"`
	LastName  string         `json:"last_name"`
	FullName  sql.NullString `json:"full_name"`
	NickName  sql.NullString `json:"nick_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Password,
		arg.FirstName,
		arg.LastName,
		arg.FullName,
		arg.NickName,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.NickName,
		&i.AvatarUrl,
		&i.ProfileUrl,
		&i.Role,
		&i.Resigned,
		&i.Gender,
		&i.Phone,
		&i.Address,
		&i.Position,
		&i.DateOfBirth,
		&i.Password,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFollow = `-- name: DeleteFollow :exec
DELETE FROM auth.follows WHERE follower_id = $1 AND following_id = $2
`

type DeleteFollowParams struct {
	FollowerID  uuid.UUID `json:"follower_id"`
	FollowingID uuid.UUID `json:"following_id"`
}

func (q *Queries) DeleteFollow(ctx context.Context, arg DeleteFollowParams) error {
	_, err := q.db.ExecContext(ctx, deleteFollow, arg.FollowerID, arg.FollowingID)
	return err
}

const deleteKeyByID = `-- name: DeleteKeyByID :exec
DELETE FROM auth.keys WHERE id = $1
`

func (q *Queries) DeleteKeyByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteKeyByID, id)
	return err
}

const deleteKeyByUserID = `-- name: DeleteKeyByUserID :exec
DELETE FROM auth.keys WHERE user_id = $1
`

func (q *Queries) DeleteKeyByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteKeyByUserID, userID)
	return err
}

const findKeyByRefreshToken = `-- name: FindKeyByRefreshToken :one
SELECT id, user_id, public_key, private_key, refresh_token, refresh_tokens_used, created_at, updated_at FROM auth.keys WHERE refresh_token = $1
`

func (q *Queries) FindKeyByRefreshToken(ctx context.Context, refreshToken sql.NullString) (AuthKey, error) {
	row := q.db.QueryRowContext(ctx, findKeyByRefreshToken, refreshToken)
	var i AuthKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.PrivateKey,
		&i.RefreshToken,
		pq.Array(&i.RefreshTokensUsed),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findKeyByRefreshTokenUsed = `-- name: FindKeyByRefreshTokenUsed :one
SELECT id, user_id, public_key, private_key, refresh_token, refresh_tokens_used, created_at, updated_at FROM auth.keys WHERE refresh_tokens_used = $1
`

func (q *Queries) FindKeyByRefreshTokenUsed(ctx context.Context, refreshTokensUsed []string) (AuthKey, error) {
	row := q.db.QueryRowContext(ctx, findKeyByRefreshTokenUsed, pq.Array(refreshTokensUsed))
	var i AuthKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.PrivateKey,
		&i.RefreshToken,
		pq.Array(&i.RefreshTokensUsed),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findKeyByUserID = `-- name: FindKeyByUserID :one
SELECT id, user_id, public_key, private_key, refresh_token, refresh_tokens_used, created_at, updated_at FROM auth.keys WHERE user_id = $1
`

func (q *Queries) FindKeyByUserID(ctx context.Context, userID uuid.UUID) (AuthKey, error) {
	row := q.db.QueryRowContext(ctx, findKeyByUserID, userID)
	var i AuthKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.PrivateKey,
		&i.RefreshToken,
		pq.Array(&i.RefreshTokensUsed),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFollowers = `-- name: GetFollowers :many
SELECT u.id , u.full_name, u.nick_name, u.avatar_url 
FROM auth.follows f
JOIN auth.users u ON f.follower_id = u.id
WHERE f.following_id = $1
`

type GetFollowersRow struct {
	ID        uuid.UUID      `json:"id"`
	FullName  sql.NullString `json:"full_name"`
	NickName  sql.NullString `json:"nick_name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) GetFollowers(ctx context.Context, followingID uuid.UUID) ([]GetFollowersRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowers, followingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowersRow
	for rows.Next() {
		var i GetFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.NickName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFollowing = `-- name: GetFollowing :many
SELECT u.id , u.full_name, u.nick_name, u.avatar_url 
FROM auth.follows f
JOIN auth.users u ON f.following_id = u.id
WHERE f.follower_id = $1
`

type GetFollowingRow struct {
	ID        uuid.UUID      `json:"id"`
	FullName  sql.NullString `json:"full_name"`
	NickName  sql.NullString `json:"nick_name"`
	AvatarUrl sql.NullString `json:"avatar_url"`
}

func (q *Queries) GetFollowing(ctx context.Context, followerID uuid.UUID) ([]GetFollowingRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowing, followerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowingRow
	for rows.Next() {
		var i GetFollowingRow
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.NickName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, email, first_name, last_name, full_name, nick_name, avatar_url, profile_url, role, resigned, gender, phone, address, position, date_of_birth, password, settings, created_at, updated_at FROM auth.users WHERE id = $1 AND resigned = FALSE
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.NickName,
		&i.AvatarUrl,
		&i.ProfileUrl,
		&i.Role,
		&i.Resigned,
		&i.Gender,
		&i.Phone,
		&i.Address,
		&i.Position,
		&i.DateOfBirth,
		&i.Password,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, first_name, last_name, full_name, nick_name, avatar_url, profile_url, role, resigned, gender, phone, address, position, date_of_birth, password, settings, created_at, updated_at FROM auth.users WHERE email = $1 AND resigned = FALSE
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.NickName,
		&i.AvatarUrl,
		&i.ProfileUrl,
		&i.Role,
		&i.Resigned,
		&i.Gender,
		&i.Phone,
		&i.Address,
		&i.Position,
		&i.DateOfBirth,
		&i.Password,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, email, first_name, last_name, full_name, nick_name, avatar_url, profile_url, role, resigned, gender, phone, address, position, date_of_birth, password, settings, created_at, updated_at FROM auth.users 
WHERE resigned = FALSE AND full_name LIKE COALESCE('%'||$1||'%','%%')
LIMIT $2
OFFSET $3
`

type GetUsersParams struct {
	Column1 sql.NullString `json:"column_1"`
	Limit   int32          `json:"limit"`
	Offset  int32          `json:"offset"`
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]AuthUser, error) {
	rows, err := q.db.QueryContext(ctx, getUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthUser
	for rows.Next() {
		var i AuthUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.FullName,
			&i.NickName,
			&i.AvatarUrl,
			&i.ProfileUrl,
			&i.Role,
			&i.Resigned,
			&i.Gender,
			&i.Phone,
			&i.Address,
			&i.Position,
			&i.DateOfBirth,
			&i.Password,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersBirthDayByCurrentDay = `-- name: GetUsersBirthDayByCurrentDay :many
SELECT id, email, first_name, last_name, full_name, nick_name, avatar_url, profile_url, role, resigned, gender, phone, address, position, date_of_birth, password, settings, created_at, updated_at FROM auth.users 
WHERE resigned = FALSE AND EXTRACT(MONTH FROM date_of_birth) = EXTRACT(MONTH FROM CURRENT_DATE)
AND EXTRACT(DAY FROM date_of_birth) = EXTRACT(DAY FROM CURRENT_DATE)
`

func (q *Queries) GetUsersBirthDayByCurrentDay(ctx context.Context) ([]AuthUser, error) {
	rows, err := q.db.QueryContext(ctx, getUsersBirthDayByCurrentDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthUser
	for rows.Next() {
		var i AuthUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.FullName,
			&i.NickName,
			&i.AvatarUrl,
			&i.ProfileUrl,
			&i.Role,
			&i.Resigned,
			&i.Gender,
			&i.Phone,
			&i.Address,
			&i.Position,
			&i.DateOfBirth,
			&i.Password,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersBirthDayByCurrentMonth = `-- name: GetUsersBirthDayByCurrentMonth :many
SELECT id, email, first_name, last_name, full_name, nick_name, avatar_url, profile_url, role, resigned, gender, phone, address, position, date_of_birth, password, settings, created_at, updated_at FROM auth.users 
WHERE 
    resigned = FALSE AND EXTRACT(MONTH FROM date_of_birth) = EXTRACT(MONTH FROM CURRENT_DATE)
`

func (q *Queries) GetUsersBirthDayByCurrentMonth(ctx context.Context) ([]AuthUser, error) {
	rows, err := q.db.QueryContext(ctx, getUsersBirthDayByCurrentMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthUser
	for rows.Next() {
		var i AuthUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.FullName,
			&i.NickName,
			&i.AvatarUrl,
			&i.ProfileUrl,
			&i.Role,
			&i.Resigned,
			&i.Gender,
			&i.Phone,
			&i.Address,
			&i.Position,
			&i.DateOfBirth,
			&i.Password,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersInviteGroup = `-- name: GetUsersInviteGroup :many
SELECT id, email, first_name, last_name, full_name, nick_name, avatar_url, profile_url, role, resigned, gender, phone, address, position, date_of_birth, password, settings, created_at, updated_at FROM auth.users 
WHERE 
    resigned = FALSE AND id != ANY($1::uuid[])
LIMIT $2
OFFSET $3
`

type GetUsersInviteGroupParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) GetUsersInviteGroup(ctx context.Context, arg GetUsersInviteGroupParams) ([]AuthUser, error) {
	rows, err := q.db.QueryContext(ctx, getUsersInviteGroup, pq.Array(arg.Column1), arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuthUser
	for rows.Next() {
		var i AuthUser
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.FullName,
			&i.NickName,
			&i.AvatarUrl,
			&i.ProfileUrl,
			&i.Role,
			&i.Resigned,
			&i.Gender,
			&i.Phone,
			&i.Address,
			&i.Position,
			&i.DateOfBirth,
			&i.Password,
			&i.Settings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKeyByUserID = `-- name: UpdateKeyByUserID :one
UPDATE auth.keys 
SET
    public_key = COALESCE($1,public_key),
    private_key = COALESCE($2,private_key),
    refresh_token = COALESCE($3,refresh_token),
    refresh_tokens_used = COALESCE($4,refresh_tokens_used)
WHERE user_id = $5 RETURNING id, user_id, public_key, private_key, refresh_token, refresh_tokens_used, created_at, updated_at
`

type UpdateKeyByUserIDParams struct {
	PublicKey         sql.NullString `json:"public_key"`
	PrivateKey        sql.NullString `json:"private_key"`
	RefreshToken      sql.NullString `json:"refresh_token"`
	RefreshTokensUsed []string       `json:"refresh_tokens_used"`
	UserID            uuid.UUID      `json:"user_id"`
}

func (q *Queries) UpdateKeyByUserID(ctx context.Context, arg UpdateKeyByUserIDParams) (AuthKey, error) {
	row := q.db.QueryRowContext(ctx, updateKeyByUserID,
		arg.PublicKey,
		arg.PrivateKey,
		arg.RefreshToken,
		pq.Array(arg.RefreshTokensUsed),
		arg.UserID,
	)
	var i AuthKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PublicKey,
		&i.PrivateKey,
		&i.RefreshToken,
		pq.Array(&i.RefreshTokensUsed),
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE auth.users 
SET
    avatar_url = COALESCE($1,avatar_url),
    profile_url = COALESCE($2,profile_url),
    gender = COALESCE($3,gender),
    phone = COALESCE($4,phone),
    address = COALESCE($5,address),
    date_of_birth = COALESCE($6,date_of_birth),
    position = COALESCE($7,position),
    settings = COALESCE($8,settings)
WHERE id = $9 RETURNING id, email, first_name, last_name, full_name, nick_name, avatar_url, profile_url, role, resigned, gender, phone, address, position, date_of_birth, password, settings, created_at, updated_at
`

type UpdateUserParams struct {
	AvatarUrl   sql.NullString        `json:"avatar_url"`
	ProfileUrl  sql.NullString        `json:"profile_url"`
	Gender      sql.NullBool          `json:"gender"`
	Phone       sql.NullString        `json:"phone"`
	Address     sql.NullString        `json:"address"`
	DateOfBirth sql.NullTime          `json:"date_of_birth"`
	Position    sql.NullString        `json:"position"`
	Settings    pqtype.NullRawMessage `json:"settings"`
	ID          uuid.UUID             `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (AuthUser, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.AvatarUrl,
		arg.ProfileUrl,
		arg.Gender,
		arg.Phone,
		arg.Address,
		arg.DateOfBirth,
		arg.Position,
		arg.Settings,
		arg.ID,
	)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.FullName,
		&i.NickName,
		&i.AvatarUrl,
		&i.ProfileUrl,
		&i.Role,
		&i.Resigned,
		&i.Gender,
		&i.Phone,
		&i.Address,
		&i.Position,
		&i.DateOfBirth,
		&i.Password,
		&i.Settings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
