http:
  routers:
    auth:
      rule: 'PathPrefix(`/api/v1/auth`)'
      service: auth
    proxy:
      rule: 'PathPrefix(`/api/v1`)'
      middlewares:
        - auth
      service: proxy
    upload:
      rule: 'PathPrefix(`/api/v1/attachments`)'
      middlewares:
        - auth
      service: upload
  services:
    auth:
      loadBalancer:
        servers:
          - url: http://proxy:5000
    proxy:
      loadBalancer:
        servers:
          - url: http://proxy:5000
    upload:
      loadBalancer:
        servers:
          - url: http://upload:5005
  middlewares:
    auth:
      forwardAuth:
        address: "http://proxy:5000/api/v1/auth/verify"
        authResponseHeaders:
          - "Grpc-Metadata-X-Auth-User"
          - "Grpc-Metadata-X-Auth-Keystore"
          - "Grpc-Metadata-X-Auth-Keystore-Used"
        trustForwardHeader: true