log:
  level: INFO
api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

providers:
  docker:
    tls:
      cert: path/to/public.crt
      key:  path/to/private.key
  file:
    filename: /etc/traefik/dynamic-config.yml
    watch: true

metrics:
  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addServicesLabels: true

accessLog:
  filePath: "/path/to/access.log"
tracing:
  jaeger:
    localAgentHostPort: jaeger:6831