syntax="proto3";

package post.v1;

import "google/api/annotations.proto";
import "protoc-gen-openapiv2/options/annotations.proto";
import "google/protobuf/timestamp.proto";
import "auth/v1/auth.proto";
import "group/v1/group.proto";
import "upload/v1/upload.proto";
import "like/v1/like.proto";
import "comment/v1/comment.proto";

option go_package = "github.com/dinhcanh303/go-microsevices/api/post/v1";

service PostService {
    rpc CreatePost(CreatePostRequest) returns (CreatePostResponse){
        option (google.api.http) = {
            post: "/api/v1/posts"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Create Post"
            description: ""
        };
    }
    rpc GetPost(GetPostRequest) returns (GetPostResponse){
        option (google.api.http) = {
            get: "/api/v1/posts/{id}"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get Post"
            description: ""
        };
    }
    rpc GetPostNormal(GetPostNormalRequest) returns (GetPostNormalResponse){
        option (google.api.http) = {
            get: "/api/v1/posts/{id}/normal"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get Post Normal"
            description: ""
        };
    }
    rpc NewFeed(NewFeedRequest) returns (NewFeedResponse){
        option (google.api.http) = {
            get: "/api/v1/feed"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get Feed"
            description: ""
        };
    }
    rpc NewFeedGroups(NewFeedGroupsRequest) returns (NewFeedGroupsResponse){
        option (google.api.http) = {
            get: "/api/v1/groups/feed"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get New Feed of Groups"
            description: ""
        };
    }
    rpc GetPostsByGroupId(GetPostsByGroupIdRequest) returns (GetPostsByGroupIdResponse){
        option (google.api.http) = {
            get: "/api/v1/groups/{group_id}/feed"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get Posts By Group ID"
            description: ""
        };
    }
    rpc GetPostsByUserId(GetPostsByUserIdRequest) returns (GetPostsByUserIdResponse){
        option (google.api.http) = {
            get: "/api/v1/users/{user_id}/feed"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Get Posts By User ID"
            description: ""
        };
    }
    rpc UpdatePost(UpdatePostRequest) returns (UpdatePostResponse){
        option (google.api.http) = {
            put: "/api/v1/posts/{post.id}"
            body: "*"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Update Post"
            description: ""
        };
    }
    rpc DeletePost(DeletePostRequest) returns (DeletePostResponse){
        option (google.api.http) = {
            delete: "/api/v1/posts/{id}"
        };
        option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_operation) = {
            summary: "Delete Post"
            description: ""
        };
    }
}
message CreatePostRequest {
    PostRequest post = 1;
}
message CreatePostResponse {
    Post post = 1;
}
message GetPostNormalRequest {
    string id = 1;
}
message GetPostNormalResponse {
    Post post = 1;
}
message GetPostRequest {
    string id = 1;
}
message GetPostResponse {
    Post post = 1;
    auth.v1.User user = 2;
    groupa.v1.Group group = 3;
    repeated upload.v1.Attachment attachments = 4;
    like.v1.LikeInfo likes = 5;
    int64 count_comments = 6;
    // repeated comment.CommentHasChildren comments = 5;
}
message NewFeedRequest {
    int32 limit = 3;
    int32 offset = 4;
}
message NewFeedResponse {
    repeated GetPostResponse posts = 1;
}
message NewFeedGroupsRequest {
    int32 limit = 3;
    int32 offset = 4;
}
message NewFeedGroupsResponse {
    repeated GetPostResponse posts = 1;
}
message GetPostsByGroupIdRequest {
    string group_id = 1;
    int32 limit = 2;
    int32 offset = 3;
}
message GetPostsByGroupIdResponse {
    repeated GetPostResponse posts = 1;
}

message GetPostsByUserIdRequest {
    string user_id = 1;
    int32 limit = 2;
    int32 offset = 3;
}
message GetPostsByUserIdResponse {
    repeated GetPostResponse posts = 1;
}
message DeletePostRequest {
    string id = 1;
}
message DeletePostResponse {
    bool deleted = 1;
}

message UpdatePostRequest {
    Post post = 1;
}
message UpdatePostResponse {
    Post post = 1;
}
message ListPostRequest {
    string id = 1;
    uint32 offset = 2;
    uint32 limit = 3;
}
message ListPostResponse {
    repeated Post post = 1;
}
message PostRequest {
    string content = 1;
    string bg_content = 2;
    int32 status = 3;
    string group_id = 4;
}
message Post {
    string id = 1;
    string content = 2;
    string bg_content = 3;
    int32 status = 4;
    string user_id = 5;
    string group_id = 6;
    google.protobuf.Timestamp created_at = 7;
    google.protobuf.Timestamp updated_at = 8;
}