app:
  name: 'reverse-proxy'
  version: '1.0.0'

http:
  host: '0.0.0.0'
  port: 5000

grpc:
  group_host: '0.0.0.0'
  group_port: 5001
  post_host: '0.0.0.0'
  post_port: 5002
  comment_host: '0.0.0.0'
  comment_port: 5003
  like_host: '0.0.0.0'
  like_port: 5004
  upload_host: '0.0.0.0'
  upload_port: 5006
  auth_host: '0.0.0.0'
  auth_port: 5007

logger:
  log_level: 'debug'
  rollbar_env: 'reverse-proxy'