// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package postgresql

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type CommentComment struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	Content         string         `json:"content"`
	ReplyTo         sql.NullString `json:"reply_to"`
	PostID          uuid.UUID      `json:"post_id"`
	ParentCommentID uuid.NullUUID  `json:"parent_comment_id"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}
