// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: query.sql

package postgresql

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const countByCommentID = `-- name: CountByCommentID :one
SELECT count(*) FROM comment.comments WHERE parent_comment_id = $1
`

func (q *Queries) CountByCommentID(ctx context.Context, parentCommentID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countByCommentID, parentCommentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countByPostID = `-- name: CountByPostID :one
SELECT count(*) FROM comment.comments WHERE post_id = $1
`

func (q *Queries) CountByPostID(ctx context.Context, postID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countByPostID, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const create = `-- name: Create :one
INSERT INTO 
    comment.comments (
        id,
		user_id,
		content,
		post_id,
		parent_comment_id,
		reply_id,
        tag_ids
    )
VALUES ( $1, $2, $3, $4, $5, $6, $7) RETURNING id, user_id, content, reply_id, tag_ids, post_id, parent_comment_id, edited, created_at, updated_at
`

type CreateParams struct {
	ID              uuid.UUID     `json:"id"`
	UserID          uuid.UUID     `json:"user_id"`
	Content         string        `json:"content"`
	PostID          uuid.UUID     `json:"post_id"`
	ParentCommentID uuid.NullUUID `json:"parent_comment_id"`
	ReplyID         uuid.NullUUID `json:"reply_id"`
	TagIds          []uuid.UUID   `json:"tag_ids"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (CommentComment, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.PostID,
		arg.ParentCommentID,
		arg.ReplyID,
		pq.Array(arg.TagIds),
	)
	var i CommentComment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.ReplyID,
		pq.Array(&i.TagIds),
		&i.PostID,
		&i.ParentCommentID,
		&i.Edited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM comment.comments WHERE id = $1 OR parent_comment_id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const deleteAllByPostID = `-- name: DeleteAllByPostID :exec
DELETE FROM comment.comments WHERE post_id = $1
`

func (q *Queries) DeleteAllByPostID(ctx context.Context, postID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllByPostID, postID)
	return err
}

const get = `-- name: Get :one
SELECT id, user_id, content, reply_id, tag_ids, post_id, parent_comment_id, edited, created_at, updated_at FROM comment.comments WHERE id = $1
`

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (CommentComment, error) {
	row := q.db.QueryRowContext(ctx, get, id)
	var i CommentComment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.ReplyID,
		pq.Array(&i.TagIds),
		&i.PostID,
		&i.ParentCommentID,
		&i.Edited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentsByCommentID = `-- name: GetCommentsByCommentID :many
SELECT id, user_id, content, reply_id, tag_ids, post_id, parent_comment_id, edited, created_at, updated_at
FROM comment.comments
WHERE parent_comment_id = $1
LIMIT $2 OFFSET $3
`

type GetCommentsByCommentIDParams struct {
	ParentCommentID uuid.NullUUID `json:"parent_comment_id"`
	Limit           int32         `json:"limit"`
	Offset          int32         `json:"offset"`
}

// ORDER BY created_at DESC
func (q *Queries) GetCommentsByCommentID(ctx context.Context, arg GetCommentsByCommentIDParams) ([]CommentComment, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsByCommentID, arg.ParentCommentID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommentComment
	for rows.Next() {
		var i CommentComment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.ReplyID,
			pq.Array(&i.TagIds),
			&i.PostID,
			&i.ParentCommentID,
			&i.Edited,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentsByPostID = `-- name: GetCommentsByPostID :many
WITH ranked_comments AS (
        SELECT
            c.id, c.user_id, c.content, c.reply_id, c.tag_ids, c.post_id, c.parent_comment_id, c.edited, c.created_at, c.updated_at,
            ROW_NUMBER() OVER (PARTITION BY parent_comment_id ORDER BY created_at) AS row_num
        FROM
            comment.comments c
        WHERE
            c.parent_comment_id IN (
                SELECT id
                FROM comment.comments
                WHERE post_id = $1 AND parent_comment_id IS NULL
                LIMIT $2 OFFSET $3
            )
)
SELECT tb.id, tb.user_id, tb.content, tb.reply_id, tb.tag_ids, tb.post_id, tb.parent_comment_id, tb.created_at, tb.updated_at
FROM
(
    SELECT 
    tb1.id,
	tb1.user_id,
	tb1.content,
	tb1.reply_id,
    tb1.tag_ids,
	tb1.post_id,
	tb1.parent_comment_id,
	tb1.created_at,
	tb1.updated_at
	FROM (
		SELECT tb2.id, tb2.user_id, tb2.content, tb2.reply_id, tb2.tag_ids, tb2.post_id, tb2.parent_comment_id, tb2.edited, tb2.created_at, tb2.updated_at FROM comment.comments AS tb2
		WHERE tb2.post_id = $1 AND tb2.parent_comment_id IS NULL
		LIMIT $2 OFFSET $3
	)  AS tb1
UNION
	SELECT 
	child.id,
    child.user_id,
    child.content,
    child.reply_id,
    child.tag_ids,
    child.post_id,
    child.parent_comment_id,
    child.created_at,
    child.updated_at
	FROM (
        
		SELECT id, user_id, content, reply_id, tag_ids, post_id, parent_comment_id, edited, created_at, updated_at, row_num
		FROM ranked_comments
		WHERE row_num = 1
	) AS child
) AS tb ORDER BY created_at
`

type GetCommentsByPostIDParams struct {
	PostID uuid.UUID `json:"post_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type GetCommentsByPostIDRow struct {
	ID              uuid.UUID     `json:"id"`
	UserID          uuid.UUID     `json:"user_id"`
	Content         string        `json:"content"`
	ReplyID         uuid.NullUUID `json:"reply_id"`
	TagIds          []uuid.UUID   `json:"tag_ids"`
	PostID          uuid.UUID     `json:"post_id"`
	ParentCommentID uuid.NullUUID `json:"parent_comment_id"`
	CreatedAt       time.Time     `json:"created_at"`
	UpdatedAt       time.Time     `json:"updated_at"`
}

func (q *Queries) GetCommentsByPostID(ctx context.Context, arg GetCommentsByPostIDParams) ([]GetCommentsByPostIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsByPostID, arg.PostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsByPostIDRow
	for rows.Next() {
		var i GetCommentsByPostIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.ReplyID,
			pq.Array(&i.TagIds),
			&i.PostID,
			&i.ParentCommentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentsByPostID2 = `-- name: GetCommentsByPostID2 :many
SELECT id, user_id, content, reply_id, tag_ids, post_id, parent_comment_id, edited, created_at, updated_at 
FROM comment.comments 
WHERE post_id = $1 AND parent_comment_id is not null
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetCommentsByPostID2Params struct {
	PostID uuid.UUID `json:"post_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) GetCommentsByPostID2(ctx context.Context, arg GetCommentsByPostID2Params) ([]CommentComment, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsByPostID2, arg.PostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommentComment
	for rows.Next() {
		var i CommentComment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.ReplyID,
			pq.Array(&i.TagIds),
			&i.PostID,
			&i.ParentCommentID,
			&i.Edited,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :one
UPDATE comment.comments 
SET
    content = COALESCE($1,content),
    reply_id = COALESCE($2,reply_id),
    tag_ids = COALESCE($3,tag_ids)
WHERE id = $4 RETURNING id, user_id, content, reply_id, tag_ids, post_id, parent_comment_id, edited, created_at, updated_at
`

type UpdateParams struct {
	Content sql.NullString `json:"content"`
	ReplyID uuid.NullUUID  `json:"reply_id"`
	TagIds  []uuid.UUID    `json:"tag_ids"`
	ID      uuid.UUID      `json:"id"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (CommentComment, error) {
	row := q.db.QueryRowContext(ctx, update,
		arg.Content,
		arg.ReplyID,
		pq.Array(arg.TagIds),
		arg.ID,
	)
	var i CommentComment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.ReplyID,
		pq.Array(&i.TagIds),
		&i.PostID,
		&i.ParentCommentID,
		&i.Edited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
