// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0
// source: query.sql

package postgresql

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const countByCommentID = `-- name: CountByCommentID :one
SELECT count(*) FROM comment.comments WHERE parent_comment_id = $1
`

func (q *Queries) CountByCommentID(ctx context.Context, parentCommentID uuid.NullUUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countByCommentID, parentCommentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countByPostID = `-- name: CountByPostID :one
SELECT count(*) FROM comment.comments WHERE post_id = $1
`

func (q *Queries) CountByPostID(ctx context.Context, postID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countByPostID, postID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const create = `-- name: Create :one
INSERT INTO 
    comment.comments (
        id,
		user_id,
		content,
		post_id,
		parent_comment_id,
		reply_to
    )
VALUES ($1, $2, $3, $4 ,$5 , $6) RETURNING id, user_id, content, reply_to, post_id, parent_comment_id, created_at, updated_at
`

type CreateParams struct {
	ID              uuid.UUID      `json:"id"`
	UserID          uuid.UUID      `json:"user_id"`
	Content         string         `json:"content"`
	PostID          uuid.UUID      `json:"post_id"`
	ParentCommentID uuid.NullUUID  `json:"parent_comment_id"`
	ReplyTo         sql.NullString `json:"reply_to"`
}

func (q *Queries) Create(ctx context.Context, arg CreateParams) (CommentComment, error) {
	row := q.db.QueryRowContext(ctx, create,
		arg.ID,
		arg.UserID,
		arg.Content,
		arg.PostID,
		arg.ParentCommentID,
		arg.ReplyTo,
	)
	var i CommentComment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.ReplyTo,
		&i.PostID,
		&i.ParentCommentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const delete = `-- name: Delete :exec
DELETE FROM comment.comments WHERE id = $1 OR parent_comment_id = $1
`

func (q *Queries) Delete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, delete, id)
	return err
}

const deleteAllByPostID = `-- name: DeleteAllByPostID :exec
DELETE FROM comment.comments WHERE post_id = $1
`

func (q *Queries) DeleteAllByPostID(ctx context.Context, postID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteAllByPostID, postID)
	return err
}

const get = `-- name: Get :one
SELECT id, user_id, content, reply_to, post_id, parent_comment_id, created_at, updated_at FROM comment.comments WHERE id = $1
`

func (q *Queries) Get(ctx context.Context, id uuid.UUID) (CommentComment, error) {
	row := q.db.QueryRowContext(ctx, get, id)
	var i CommentComment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.ReplyTo,
		&i.PostID,
		&i.ParentCommentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listByPostID = `-- name: ListByPostID :many
SELECT id, user_id, content, reply_to, post_id, parent_comment_id, created_at, updated_at FROM comment.comments WHERE post_id = $1
`

func (q *Queries) ListByPostID(ctx context.Context, postID uuid.UUID) ([]CommentComment, error) {
	rows, err := q.db.QueryContext(ctx, listByPostID, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommentComment
	for rows.Next() {
		var i CommentComment
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.ReplyTo,
			&i.PostID,
			&i.ParentCommentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const update = `-- name: Update :one
UPDATE comment.comments 
SET
    content = $2 ,
    reply_to = $3
WHERE id = $1 RETURNING id, user_id, content, reply_to, post_id, parent_comment_id, created_at, updated_at
`

type UpdateParams struct {
	ID      uuid.UUID      `json:"id"`
	Content string         `json:"content"`
	ReplyTo sql.NullString `json:"reply_to"`
}

func (q *Queries) Update(ctx context.Context, arg UpdateParams) (CommentComment, error) {
	row := q.db.QueryRowContext(ctx, update, arg.ID, arg.Content, arg.ReplyTo)
	var i CommentComment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.ReplyTo,
		&i.PostID,
		&i.ParentCommentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
